export const ActivitiesListData = [
  {
    key: "1",
    Title: "We scheduled a meeting for next week",
    ActivityType: "Meeting",
    DueDate: "25 Sep 2025, 12:12 pm",
    Owner: "Hendry Milner",
    CreatedAt: "22 Sep 2025, 10:14 am",
    Image: "avatar-01.jpg",
  },
  {
    key: "2",
    Title: "Had conversation with Fred regarding task",
    ActivityType: "Calls",
    DueDate: "29 Sep 2025, 04:12 pm",
    Owner: "Theresa Nelson",
    CreatedAt: "27 Sep 2025, 03:26 pm",
    Image: "avatar-26.jpg",
  },
  {
    key: "3",
    Title: "Analysing latest time estimation for new project",
    ActivityType: "Email",
    DueDate: "11 Oct 2025, 05:00 pm",
    Owner: "Guilory Berggren",
    CreatedAt: "03 Oct 2025, 03:53 pm",
    Image: "avatar-06.jpg",
  },
  {
    key: "4",
    Title: "Store and manage contact data",
    ActivityType: "Task",
    DueDate: "19 Oct 2025, 02:35 pm",
    Owner: "Jami Carlile",
    CreatedAt: "14 Oct 2025, 01:25 pm",
    Image: "avatar-13.jpg",
  },
  {
    key: "5",
    Title: "Will have a meeting before project start",
    ActivityType: "Meeting",
    DueDate: "27 Oct 2025, 12:30 pm",
    Owner: "Theresa Nelson",
    CreatedAt: "21 Oct 2025, 03:00 pm",
    Image: "avatar-17.jpg",
  },
  {
    key: "6",
    Title: "Call John and discuss about project",
    ActivityType: "Calls",
    DueDate: "12 Nov 2025, 10:20 pm",
    Owner: "Smith Cooper",
    CreatedAt: "02 Nov 2025, 05:35 pm",
    Image: "avatar-14.jpg",
  },
  {
    key: "7",
    Title: "Built landing pages",
    ActivityType: "Task",
    DueDate: "25 Nov 2025, 01:40 pm",
    Owner: "Martin Lewis",
    CreatedAt: "20 Nov 2025, 08:20 am",
    Image: "avatar-20.jpg",
  },
  {
    key: "8",
    Title: "Regarding latest updates in project",
    ActivityType: "Email",
    DueDate: "30 Nov 2025, 09:20 pm",
    Owner: "Newell Egan",
    CreatedAt: "25 Nov 2025, 07:20 pm",
    Image: "avatar-15.jpg",
  },
  {
    key: "9",
    Title: "Discussed budget proposal with Edwin",
    ActivityType: "Calls",
    DueDate: "08 Dec 2025, 04:35 pm",
    Owner: "Janet Carlson",
    CreatedAt: "01 Dec 2025, 10:45 am",
    Image: "avatar-04.jpg",
  },
  {
    key: "10",
    Title: "Attach final proposal for upcoming project",
    ActivityType: "Email",
    DueDate: "19 Dec 2025, 02:20 pm",
    Owner: "Craig Brown",
    CreatedAt: "10 Dec 2025, 06:30 pm",
    Image: "avatar-21.jpg",
  },
];

export const ActivitiesCallsData = [
  {
    key: "1",
    Title: "Had conversation with Fred regarding task",
    ActivityType: "Calls",
    DueDate: "29 Sep 2025, 04:12 pm",
    Owner: "Theresa Nelson",
    CreatedAt: "27 Sep 2025, 03:26 pm",
    Image: "avatar-26.jpg",
  },
  {
    key: "2",
    Title: "Call John and discuss about project",
    ActivityType: "Calls",
    DueDate: "12 Nov 2025, 10:20 pm",
    Owner: "Smith Cooper",
    CreatedAt: "02 Nov 2025, 05:35 pm",
    Image: "avatar-14.jpg",
  },
  {
    key: "3",
    Title: "Discussed budget proposal with Edwin",
    ActivityType: "Calls",
    DueDate: "08 Dec 2025, 04:35 pm",
    Owner: "Janet Carlson",
    CreatedAt: "01 Dec 2025, 10:45 am",
    Image: "avatar-04.jpg",
  },
];

export const ActivitiesMails = [
  {
    key: "1",
    Title: "Analysing latest time estimation for new project",
    ActivityType: "Email",
    DueDate: "11 Oct 2025, 05:00 pm",
    Owner: "Guilory Berggren",
    CreatedAt: "03 Oct 2025, 03:53 pm",
    Image: "avatar-06.jpg",
  },
  {
    key: "2",
    Title: "Regarding latest updates in project",
    ActivityType: "Email",
    DueDate: "30 Nov 2025, 09:20 pm",
    Owner: "Newell Egan",
    CreatedAt: "25 Nov 2025, 07:20 pm",
    Image: "avatar-15.jpg",
  },
  {
    key: "3",
    Title: "Attach final proposal for upcoming project",
    ActivityType: "Email",
    DueDate: "19 Dec 2025, 02:20 pm",
    Owner: "Craig Brown",
    CreatedAt: "10 Dec 2025, 06:30 pm",
    Image: "avatar-21.jpg",
  },
];

export const ActivitiesTasks = [
  {
    key: "4",
    Title: "Store and manage contact data",
    ActivityType: "Task",
    DueDate: "19 Oct 2025, 02:35 pm",
    Owner: "Jami Carlile",
    CreatedAt: "14 Oct 2025, 01:25 pm",
    Image: "avatar-13.jpg",
  },
  {
    key: "7",
    Title: "Built landing pages",
    ActivityType: "Task",
    DueDate: "25 Nov 2025, 01:40 pm",
    Owner: "Martin Lewis",
    CreatedAt: "20 Nov 2025, 08:20 am",
    Image: "avatar-20.jpg",
  },
];

export const ActivitiesMeetings = [
  {
    key: "1",
    Title: "We scheduled a meeting for next week",
    ActivityType: "Meeting",
    DueDate: "25 Sep 2025, 12:12 pm",
    Owner: "Hendry Milner",
    CreatedAt: "22 Sep 2025, 10:14 am",
    Image: "avatar-01.jpg",
  },
  {
    key: "2",
    Title: "Will have a meeting before project start",
    ActivityType: "Meeting",
    DueDate: "27 Oct 2025, 12:30 pm",
    Owner: "Theresa Nelson",
    CreatedAt: "21 Oct 2025, 03:00 pm",
    Image: "avatar-17.jpg",
  },
];