export const BlogCommentsListData = [
  {
    key: "1",
    Name: "Darlee Robertson",
    Image: "avatar-19.jpg",
    Role: "Facility Manager",
    Email: "robertson@example.com",
    Comment: "Great tips! I’ll definitely try these out with my sales team.",
    Created_Date: "17 Dec 2025",
    Status: "Publish",
  },
  {
    key: "2",
    Name: "Sharon Roy",
    Image: "avatar-20.jpg",
    Role: "Installer",
    Email: "sharon@example.com",
    Comment: "Automation is a game-changer. Thanks for sharing this.",
    Created_Date: "11 Dec 2025",
    Status: "Publish",
  },
  {
    key: "3",
    Name: "Vaughan Lewis",
    Image: "avatar-21.jpg",
    Role: "Senior Manager",
    Email: "vaughan12@example.com",
    Comment: "Can you recommend tools that work best for integration?",
    Created_Date: "23 Nov 2025",
    Status: "Publish",
  },
  {
    key: "4",
    Name: "Jessica Louise",
    Image: "avatar-21.jpg",
    Role: "Test Engineer",
    Email: "jessica13@example.com",
    Comment: "Really helpful guide. Saved me from repeating old errors.",
    Created_Date: "12 Nov 2025",
    Status: "Publish",
  },
  {
    key: "5",
    Name: "Carol Thomas",
    Image: "avatar-23.jpg",
    Role: "UI /UX Designer",
    Email: "caroltho3@example.com",
    Comment: "Looking forward to trying out these new features!",
    Created_Date: "07 Nov 2025",
    Status: "Publish",
  },
  {
    key: "6",
    Name: "Dawn Mercha",
    Image: "avatar-16.jpg",
    Role: "Technician",
    Email: "dawnmercha@example.com",
    Comment: "Love the focus on data-driven decisions.",
    Created_Date: "15 Oct 2025",
    Status: "Unpublish",
  },
  {
    key: "7",
    Name: "Rachel Hampton",
    Image: "avatar-22.jpg",
    Role: "Software Developer",
    Email: "rachel@example.com",
    Comment: "Customization has really improved our workflow.",
    Created_Date: "04 Oct 2025",
    Status: "Unpublish",
  },
  {
    key: "8",
    Name: "Jonelle Curtiss",
    Image: "avatar-24.jpg",
    Role: "Supervisor",
    Email: "jonelle@example.com",
    Comment: "Excited to see how these trends will shape the future.",
    Created_Date: "29 Sep 2025",
    Status: "Publish",
  },
  {
    key: "9",
    Name: "Jonathan Smith",
    Image: "avatar-25.jpg",
    Role: "Team Lead Dev",
    Email: "jonathan@example.com",
    Comment: "User training is so important. Thanks for the insights.",
    Created_Date: "25 Sep 2025",
    Status: "Unpublish",
  },
  {
    key: "10",
    Name: "Brook Carter",
    Image: "avatar-26.jpg",
    Role: "Team Lead Dev",
    Email: "brook@example.com",
    Comment: "This is a must-read for anyone handling sensitive data.",
    Created_Date: "17 Sep 2025",
    Status: "Publish",
  },
];
