export const campaignArchieveListData = [
  {
    key: "1",
    Name: "Distribution",
    Type: "Public Relations",
    Progress1: "40.5% ",
    Progress2: "20.5%",
    Progress3: "30.5%",
    Progress4: "70.5%",
    Progress5: "35.0%",
    Members: "3+",
    Status: "Success",
  },
  {
    key: "2",
    Name: "Merchandising",
    Type: "Content Marketing",
    Progress1: "64.5% ",
    Progress2: "97.0%",
    Progress3: "14.5%",
    Progress4: "38.0%",
    Progress5: "53.0%",
    Members: "3+",
    Status: "Pending",
  },
  {
    key: "3",
    Name: "Pricing",
    Type: "Social Marketing",
   Progress1: "64.0% ",
    Progress2: "97.0%",
    Progress3: "14.5%",
    Progress4: "38.5%",
    Progress5: "53.0%",
    Members: "3+",
    Status: "Success",
  },
  {
    key: "4",
    Name: "Increased sales",
    Type: "Brand",
    Progress1: "32.5% ",
    Progress2: "57.0%",
    Progress3: "26.3%",
    Progress4: "65.8%",
    Progress5: "17.4%",
    Members: "3+",
    Status: "Success",
  },
];
