export const campaignListData = [
  {
    key: "1",
    Name: "Distribution",
    Type: "Public Relations",
    Progress1: "40.5% ",
    Progress2: "20.5%",
    Progress3: "30.5%",
    Progress4: "70.5%",
    Progress5: "35.0%",
    Members: "3+",
    Status: "Success",
  },
  {
    key: "2",
    Name: "Merchandising",
    Type: "Content Marketing",
    Progress1: "64.5% ",
    Progress2: "97.0%",
    Progress3: "14.5%",
    Progress4: "38.0%",
    Progress5: "53.0%",
    Members: "3+",
    Status: "Pending",
  },
  {
    key: "3",
    Name: "Pricing",
    Type: "Social Marketing",
   Progress1: "64.0% ",
    Progress2: "97.0%",
    Progress3: "14.5%",
    Progress4: "38.5%",
    Progress5: "53.0%",
    Members: "3+",
    Status: "Success",
  },
  {
    key: "4",
    Name: "Increased sales",
    Type: "Brand",
    Progress1: "32.5% ",
    Progress2: "57.0%",
    Progress3: "26.3%",
    Progress4: "65.8%",
    Progress5: "17.4%",
    Members: "3+",
    Status: "Bounced",
  },
  {
    key: "5",
    Name: "Brand recognition",
    Type: "Sales",
     Progress1: "72.6% ",
    Progress2: "53.5%",
    Progress3: "16.5%",
    Progress4: "83.0%",
    Progress5: "29.3%",
    Members: "3+",
    Status: "Running",
  },
  {
    key: "6",
    Name: "Enhanced brand",
    Type: "Media",
    Progress1: "56.3% ",
    Progress2: "20.5%",
    Progress3: "30.5%",
    Progress4: "70.5%",
    Progress5: "87.8%",
    Members: "3+",
    Status: "Paused",
  },
  {
    key: "7",
    Name: "Repeat customers",
    Type: "Rebranding",
   Progress1: "63.2% ",
    Progress2: "20.5%",
    Progress3: "30.5%",
    Progress4: "70.5%",
    Progress5: "87.8%",
    Members: "3+",
    Status: "Success",
  },
  {
    key: "8",
    Name: "Competitor",
    Type: "Product launch",
   Progress1: "40.5% ",
    Progress2: "52.7%",
    Progress3: "13.5%",
    Progress4: "70.5%",
    Progress5: "35.0%",
    Members: "3+",
    Status: "Paused",
  },
];
