export const CitiesListData =  [
  {
    key: "1",
    CountryName: "United States",
    Image: "country-01.svg",
    StateName: "Indiana",
    CityName: "Indianapolis",
  },
  {
    key: "2",
    CountryName: "Canada",
    Image: "country-02.svg",
    StateName: "Alberta",
    CityName: "Calgary",
  },
  {
    key: "3",
    CountryName: "Spain",
    Image: "country-03.svg",
    StateName: "Madrid",
    CityName: "Bulgaria",
  },
  {
    key: "4",
    CountryName: "India",
    Image: "country-04.svg",
    StateName: "Tamil Nadu",
    CityName: "Trichy",
  },
  {
    key: "5",
    CountryName: "Brazil",
    Image: "country-05.svg",
    StateName: "Alagoas",
    CityName: "Porto Alegre",
  },
  {
    key: "6",
    CountryName: "Germany",
    Image: "country-06.svg",
    StateName: "Saarland",
    CityName: "Hamburg",
  },
  {
    key: "7",
    CountryName: "Mexico",
    Image: "country-07.svg",
    StateName: "Durango",
    CityName: "Guadalajara",
  },
  {
    key: "8",
    CountryName: "China",
    Image: "country-08.svg",
    StateName: "Shandong",
    CityName: "Chengdu",
  },
  {
    key: "9",
    CountryName: "Russia",
    Image: "country-09.svg",
    StateName: "Kalmykia",
    CityName: "Moscow",
  },
  {
    key: "10",
    CountryName: "Italy",
    Image: "country-10.svg",
    StateName: "Tuscany",
    CityName: "Rome",
  },
];