export const CompaniesListData = [
  {
    kye: "1",
    Image: "company-icon-01.svg",
    Name: "NovaWave LLC",
    Email: "robertson@example.com",
    Tags: "Collab",
    Owner: "Hendry Milner",
    Owner_Img: "avatar-01.jpg",
    Status: "Active",
  },
  {
    kye: "2",
    Image: "company-icon-02.svg",
    Name: "BlueSky Industries",
    Email: "sharon@example.com",
    Tags: "Collab",
    Owner: "Guilory Berggren",
    Owner_Img: "avatar-06.jpg",
    Status: "Inactive",
  },
  {
    kye: "3",
    Image: "company-icon-03.svg",
    Name: "SilverHawk",
    Email: "vaughan12@example.com",
    Tags: "Collab",
    Owner: "Jami Carlile",
    Owner_Img: "avatar-13.jpg",
    Status: "Active",
  },
  {
    kye: "4",
    Image: "company-icon-04.svg",
    Name: "SummitPeak",
    Email: "jessica13@example.com",
    Tags: "Collab",
    Owner: "Theresa Nelson",
    Owner_Img: "avatar-17.jpg",
    Status: "Active",
  },
  {
    kye: "5",
    Image: "company-icon-04.svg",
    Name: "RiverStone Ventur",
    Email: "caroltho3@example.com",
    Tags: "Collab",
    Owner: "Smith Cooper",
    Owner_Img: "avatar-14.jpg",
    Status: "Active",
  },
  {
    kye: "6",
    Image: "company-icon-05.svg",
    Name: "Bright Bridge Grp",
    Email: "dawnmercha@example.com",
    Tags: "Collab",
    Owner: "Martin Lewis",
    Owner_Img: "avatar-20.jpg",
    Status: "Active",
  },
  {
    kye: "7",
    Image: "company-icon-06.svg",
    Name: "CoastalStar Co.",
    Email: "rachel@example.com",
    Tags: "Collab",
    Owner: "Newell Egan",
    Owner_Img: "avatar-15.jpg",
    Status: "Active",
  },
  {
    kye: "8",
    Image: "company-icon-07.svg",
    Name: "HarborView",
    Email: "jonelle@example.com",
    Tags: "Promotion",
    Owner: "Janet Carlson",
    Owner_Img: "avatar-04.jpg",
    Status: "Active",
  },
  {
    kye: "9",
    Image: "company-icon-08.svg",
    Name: "Golden Gate Ltd",
    Email: "jonathan@example.com",
    Tags: "Promotion",
    Owner: "Craig Brown",
    Owner_Img: "avatar-21.jpg",
    Status: "Active",
  },
  {
    kye: "10",
    Image: "company-icon-09.svg",
    Name: "Redwood Inc",
    Email: "brook@example.com",
    Tags: "Promotion",
    Owner: "Daniel Byrne",
    Owner_Img: "avatar-23.jpg",
    Status: "Active",
  },
];
