export const CompanyReportListData =[
  {
    key: "1",
    Name: "NovaWave LLC",
    Email: "robertson@example.com",
    Tags: "Collab",
    Owner: "Hendry Milner",
    OwnerImage: "avatar-06.jpg",
    Image: "company-01.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "2",
    Name: "BlueSky Industries",
    Email: "sharon@example.com",
    Tags: "Collab",
    Owner: "Guilory Berggren",
    OwnerImage: "avatar-05.jpg",
    Image: "company-02.svg",
    Contact: "",
    Status: "Inactive",
  },
  {
    key: "3",
    Name: "SilverHawk",
    Email: "vaughan12@example.com",
    Tags: "Collab",
    Owner: "Jami Carlile",
    OwnerImage: "avatar-04.jpg",
    Image: "company-03.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "4",
    Name: "SummitPeak",
    Email: "jessica13@example.com",
    Tags: "Collab",
    Owner: "Theresa Nelson",
    OwnerImage: "avatar-08.jpg",
    Image: "company-04.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "5",
    Name: "RiverStone Ventur",
    Email: "caroltho3@example.com",
    Tags: "Collab",
    Owner: "Smith Cooper",
    OwnerImage: "avatar-02.jpg",
    Image: "company-05.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "6",
    Name: "Bright Bridge Grp",
    Email: "dawnmercha@example.com",
    Tags: "Collab",
    Owner: "Martin Lewis",
    OwnerImage: "avatar-01.jpg",
    Image: "company-06.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "7",
    Name: "CoastalStar Co.",
    Email: "rachel@example.com",
    Tags: "Collab",
    Owner: "Newell Egan",
    OwnerImage: "avatar-17.jpg",
    Image: "company-07.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "8",
    Name: "HarborView",
    Email: "jonelle@example.com",
    Tags: "Promotion",
    Owner: "Janet Carlson",
    OwnerImage: "avatar-16.jpg",
    Image: "company-08.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "9",
    Name: "Golden Gate Ltd",
    Email: "jonathan@example.com",
    Tags: "Promotion",
    Owner: "Craig Brown",
    OwnerImage: "avatar-15.jpg",
    Image: "company-09.svg",
    Contact: "",
    Status: "Active",
  },
  {
    key: "10",
    Name: "Redwood Inc",
    Email: "brook@example.com",
    Tags: "Promotion",
    Owner: "Daniel Byrne",
    OwnerImage: "avatar-14.jpg",
    Image: "company-10.svg",
    Contact: "",
    Status: "Active",
  },
];