export const ContractListData = [
  {
    key: "1",
    ContractID: "#1493024",
    Subject: "SEO Proposal",
    Customer: "NovaWave LLC",
    Image: "company-icon-01.svg",
    ContractType: "Contracts under Seal",
    StartDate: "15 Aug 2024",
    EndDate: "15 May 2024",
  },
  {
    key: "2",
    ContractID: "#1493023",
    Subject: "Web Design",
    Customer: "Redwood Inc",
    Image: "company-icon-02.svg",
    ContractType: "Implied Contracts",
    StartDate: "15 Sep 2024",
    EndDate: "15 Apr 2024",
  },
  {
    key: "3",
    ContractID: "#1493022",
    Subject: "Logo & Branding",
    Customer: "HarborView",
    Image: "company-icon-03.svg",
    ContractType: "Implied Contracts",
    StartDate: "15 Nov 2024",
    EndDate: "15 Mar 2024",
  },
  {
    key: "4",
    ContractID: "#1493021",
    Subject: "Development",
    Customer: "CoastalStar Co.",
    Image: "company-icon-04.svg",
    ContractType: "Executory Contracts",
    StartDate: "15 Jun 2024",
    EndDate: "15 Feb 2024",
  },
  {
    key: "5",
    ContractID: "#1493020",
    Subject: "SEO Proposal",
    Customer: "RiverStone Ventur",
    Image: "company-icon-05.svg",
    ContractType: "Voidable Contracts",
    StartDate: "15 Oct 2024",
    EndDate: "15 Jan 2024",
  },
  {
    key: "6",
    ContractID: "#1493019",
    Subject: "Web Design",
    Customer: "Summit  Peak",
    Image: "company-icon-06.svg",
    ContractType: "Unilateral Contracts",
    StartDate: "08 Aug 2024",
    EndDate: "15 Dec 2025",
  },
  {
    key: "7",
    ContractID: "#1493018",
    Subject: "Logo",
    Customer: "Silver Hawk",
    Image: "company-icon-07.svg",
    ContractType: "Unconscionable",
    StartDate: "25 Jan 2025",
    EndDate: "15 Nov 2025",
  },
  {
    key: "8",
    ContractID: "#1493017",
    Subject: "Branding",
    Customer: "BlueSky Industries",
    Image: "company-icon-08.svg",
    ContractType: "Express Contracts",
    StartDate: "12 Aug 2024",
    EndDate: "15 Sep 2025",
  },
  {
    key: "9",
    ContractID: "#1493018",
    Subject: "Development",
    Customer: "Golden Gate Ltd",
    Image: "company-icon-09.svg",
    ContractType: "Contracts under Seal",
    StartDate: "07 Dec 2024",
    EndDate: "15 Aug 2025",
  },
];