export const ContactsListData = [
  {
    key: "1",
    Name: "Darlee Robertson",
    Role: "Facility Manager",
    Phone: "1234567890",
    Tags: "Collab",
    Location: "USA",
    Rating: "4.2",
    Image: "avatar-19.jpg",
    Flags: "us.svg",
    Status: "Active",
  },
  {
    key: "2",
    Name: "Sharon Roy",
    Role: "Installer",
    Phone: "+1 989757485",
    Tags: "Promotion",
    Location: "UAE",
    Rating: "5",
    Image: "avatar-20.jpg",
    Flags: "ae.svg",
    Status: "Inactive",
  },
  {
    key: "3",
    Name: "Vaughan Lewis",
    Role: "Senior Manager",
    Phone: "+1 546555455",
    Tags: "Collab",
    Location: "Germany",
    Rating: "3.5",
    Image: "avatar-21.jpg",
    Flags: "de.svg",
    Status: "Active",
  },
  {
    key: "4",
    Name: "Jessica Louise",
    Role: "Test Engineer",
    Phone: "+1 454478787",
    Tags: "VIP",
    Location: "France",
    Rating: "4.5",
    Image: "avatar-23.jpg",
    Flags: "fr.svg",
    Status: "Active",
  },
  {
    key: "5",
    Name: "Carol Thomas",
    Role: "UI /UX Designer",
    Phone: "+1 124547845",
    Tags: "Collab",
    Location: "India",
    Rating: "4.7",
    Image: "avatar-16.jpg",
    Flags: "india.svg",
    Status: "Active",
  },
  {
    key: "6",
    Name: "Dawn Mercha",
    Role: "Technician",
    Phone: "+1 478845447",
    Tags: "VIP",
    Location: "Brazil",
    Rating: "5",
    Image: "avatar-22.jpg",
    Flags: "brazil.svg",
    Status: "Active",
  },
  {
    key: "7",
    Name: "Rachel Hampton",
    Role: "Software Developer",
    Phone: "+1 215544845",
    Tags: "Promotion",
    Location: "Mexico",
    Rating: "3.1",
    Image: "avatar-24.jpg",
    Flags: "mexico.svg",
    Status: "Active",
  },
  {
    key: "8",
    Name: "Jonelle Curtiss",
    Role: "Supervisor",
    Phone: "+1 121145471",
    Tags: "VIP",
    Location: "China",
    Rating: "5",
    Image: "avatar-25.jpg",
    Flags: "china.svg",
    Status: "Active",
  },
  {
    key: "9",
    Name: "Jonathan Smith",
    Role: "Team Lead Dev",
    Phone: "+1 321454789",
    Tags: "Collab",
    Location: "Russia",
    Rating: "2.7",
    Image: "avatar-26.jpg",
    Flags: "russia.svg",
    Status: "Active",
  },
  {
    key: "10",
    Name: "Brook Carter",
    Role: "Team Lead Dev",
    Phone: "+1 278907145",
    Tags: "Promotion",
    Location: "France",
    Rating: "3",
    Image: "avatar-01.jpg",
    Flags: "fr.svg",
    Status: "Active",
  },
];
