export const COuntriesListData = [
  {
    key: "1",
    Image: "country-01.svg",
    CountryCode: "United States",
    CountryID: "Indiana",
    CountryName: "Indianapolis",
  },
  {
    key: "2",
    Image: "country-02.svg",
    CountryCode: "Canada",
    CountryID: "Alberta",
    CountryName: "Calgary",
  },
  {
    key: "3",
    Image: "country-03.svg",
    CountryCode: "Spain",
    CountryID: "Madrid",
    CountryName: "Bulgaria",
  },
  {
    key: "4",
    Image: "country-04.svg",
    CountryCode: "India",
    CountryID: "Tamil Nadu",
    CountryName: "Trichy",
  },
  {
    key: "5",
    Image: "country-05.svg",
    CountryCode: "Brazil",
    CountryID: "Alagoas",
    CountryName: "Porto Alegre",
  },
  {
    key: "6",
    Image: "country-06.svg",
    CountryCode: "Germany",
    CountryID: "Saarland",
    CountryName: "Hamburg",
  },
  {
    key: "7",
    Image: "country-07.svg",
    CountryCode: "Mexico",
    CountryID: "Durango",
    CountryName: "Guadalajara",
  },
  {
    key: "8",
    Image: "country-08.svg",
    CountryCode: "China",
    CountryID: "Shandong",
    CountryName: "Chengdu",
  },
  {
    key: "9",
    Image: "country-09.svg",
    CountryCode: "Russia",
    CountryID: "Kalmykia",
    CountryName: "Moscow",
  },
  {
    key: "10",
    Image: "country-10.svg",
    CountryCode: "Italy",
    CountryID: "Tuscany",
    CountryName: "Rome",
  },
];