export const DataTablesData = [
  {
    key: "1",
    Name: "Tiger Nixon",
    Position: "System Architect",
    Office: "Edinburgh",
    Age: "61",
    Start_date: "2011 Apr 25",
    Salary: "$320,800",
  },
  {
    key: "2",
    Name: "Garrett Winters",
    Position: "Accountant",
    Office: "Tokyo",
    Age: "63",
    Start_date: "2011 Jul 25",
    Salary: "$170,750",
  },
  {
    key: "3",
    Name: "Ashton Cox",
    Position: "Junior Technical Author",
    Office: "San Francisco",
    Age: "66",
    Start_date: "2009 Jan 12",
    Salary: "$86,000",
  },
  {
    key: "4",
    Name: "Cedric Kelly",
    Position: "Senior Javascript Developer",
    Office: "Edinburgh",
    Age: "22",
    Start_date: "2012 Mar 29",
    Salary: "$433,060",
  },
  {
    key: "5",
    Name: "Airi Satou",
    Position: "Accountant",
    Office: "Tokyo",
    Age: "33",
    Start_date: "2008 Nov 28",
    Salary: "$162,700",
  },
  {
    key: "6",
    Name: "Brielle Williamson",
    Position: "Integration Specialist",
    Office: "New York",
    Age: "61",
    Start_date: "2012 Dec 02",
    Salary: "$372,000",
  },
  {
    key: "7",
    Name: "Herrod Chandler",
    Position: "Sales Assistant",
    Office: "San Francisco",
    Age: "59",
    Start_date: "2012 Aug 06",
    Salary: "$137,500",
  },
  {
    key: "8",
    Name: "Rhona Davidson",
    Position: "Integration Specialist",
    Office: "Tokyo",
    Age: "55",
    Start_date: "2010 Oct 14",
    Salary: "$327,900",
  },
  {
    key: "9",
    Name: "Colleen Hurst",
    Position: "Javascript Developer",
    Office: "San Francisco",
    Age: "39",
    Start_date: "2009 Sep 15",
    Salary: "$205,500",
  },
  {
    key: "10",
    Name: "Sonya Frost",
    Position: "Software Engineer",
    Office: "Edinburgh",
    Age: "23",
    Start_date: "2008 Dec 13",
    Salary: "$103,600",
  },
];
