export const DealsReportListData= [
  {
    key: "1",
    DealName: "Annual Software Subscription",
    Stage: "Appointment",
    DealValue: "$04,51,000",
    Tags: "Rated",
    ExpectedCloseDate: "25 Sep 2025",
    Probability: "90%",
    Status: "Won",
  },
  {
    key: "2",
    DealName: "CRM Onboarding Package",
    Stage: "Appointment",
    DealValue: "$03,12,500",
    Tags: "Collab",
    ExpectedCloseDate: "29 Sep 2025",
    Probability: "15 %",
    Status: "Lost",
  },
  {
    key: "3",
    DealName: "Enterprise Plan Upgrade",
    Stage: "Contact Made",
    DealValue: "$04,14,800",
    Tags: "Rejected",
    ExpectedCloseDate: "04 Oct 2025",
    Probability: "95 %",
    Status: "Won",
  },
  {
    key: "4",
    DealName: "BrightWorks Campaign",
    Stage: "Presentation",
    DealValue: "$11,14,400",
    Tags: "Rated",
    ExpectedCloseDate: "15 Oct 2025",
    Probability: "99 %",
    Status: "Won",
  },
  {
    key: "5",
    DealName: "Sales Pipeline Optimization",
    Stage: "Proposal Made",
    DealValue: "$16,11,400",
    Tags: "Rated",
    ExpectedCloseDate: "27 Oct 2025",
    Probability: "10 %",
    Status: "open",
  },
  {
    key: "6",
    DealName: "CRM Migration Project",
    Stage: "Proposal Made",
    DealValue: "$78,11,800",
    Tags: "Rated",
    ExpectedCloseDate: "07 Nov 2025",
    Probability: "70 %",
    Status: "Won",
  },
  {
    key: "7",
    DealName: "Multi-Store License Renewal",
    Stage: "Proposal Made",
    DealValue: "$09,05,947",
    Tags: "Promotion",
    ExpectedCloseDate: "12 Nov 2025",
    Probability: "10 %",
    Status: "open",
  },
  {
    key: "8",
    DealName: "Custom Feature Development",
    Stage: "Qualify To Buy",
    DealValue: "$04,51,000",
    Tags: "Rejected",
    ExpectedCloseDate: "23 Nov 2025",
    Probability: "90 %",
    Status: "Won",
  },
  {
    key: "9",
    DealName: "SkyHigh Annual Booking",
    Stage: "Qualify To Buy",
    DealValue: "$72,14,078",
    Tags: "Collab",
    ExpectedCloseDate: "11 Dec 2025",
    Probability: "40 %",
    Status: "Won",
  },
  {
    key: "10",
    DealName: "BlueOcean Funding Round",
    Stage: "Qualify To Buy",
    DealValue: "$09,05,947",
    Tags: "Collab",
    ExpectedCloseDate: "17 Dec 2025",
    Probability: "47 %",
    Status: "Lost",
  },
];