export const DealsListData = [
  {
    key: "1",
    DealName: "Collins",
    Stage: "Qualify To Buy",
    DealValue: "$04,51,000",
    Tags: "Collab",
    ExpectedCloseDate: "25 Sep 2025",
    Probability: "90%",
    Status: "Won",
  },
  {
    key: "2",
    DealName: "Konopelski",
    Stage: "Proposal Made",
    DealValue: "$03,12,500",
    Tags: "Rated",
    ExpectedCloseDate: "29 Sep 2025",
    Probability: "15 %",
    Status: "Lost",
  },
  {
    key: "3",
    DealName: "Adams",
    Stage: "Contact Made",
    DealValue: "$04,14,800",
    Tags: "Rejected",
    ExpectedCloseDate: "04 Oct 2025",
    Probability: "95 %",
    Status: "Won",
  },
  {
    key: "4",
    DealName: "Schumm",
    Stage: "Qualify To Buy",
    DealValue: "$11,14,400",
    Tags: "Collab",
    ExpectedCloseDate: "15 Oct 2025",
    Probability: "99 %",
    Status: "Won",
  },
  {
    key: "5",
    DealName: "Wisozk",
    Stage: "Presentation",
    DealValue: "$16,11,400",
    Tags: "Rated",
    ExpectedCloseDate: "27 Oct 2025",
    Probability: "10 %",
    Status: "Open",
  },
  {
    key: "6",
    DealName: "Heller",
    Stage: "Appointment",
    DealValue: "$78,11,800",
    Tags: "Rated",
    ExpectedCloseDate: "07 Nov 2025",
    Probability: "70 %",
    Status: "Won",
  },
  {
    key: "7",
    DealName: "Gutkowski",
    Stage: "Proposal Made",
    DealValue: "$09,05,947",
    Tags: "Rated",
    ExpectedCloseDate: "12 Nov 2025",
    Probability: "10 %",
    Status: "Open",
  },
  {
    key: "8",
    DealName: "Walter",
    Stage: "Qualify To Buy",
    DealValue: "$04,51,000",
    Tags: "Rejected",
    ExpectedCloseDate: "23 Nov 2025",
    Probability: "90 %",
    Status: "Won",
  },
  {
    key: "9",
    DealName: "Hansen",
    Stage: "Appointment",
    DealValue: "$72,14,078",
    Tags: "Collab",
    ExpectedCloseDate: "11 Dec 2025",
    Probability: "40 %",
    Status: "Won",
  },
  {
    key: "10",
    DealName: "Leuschke",
    Stage: "Proposal Made",
    DealValue: "$09,05,947",
    Tags: "Rated",
    ExpectedCloseDate: "17 Dec 2025",
    Probability: "47 %",
    Status: "Lost",
  },
];