export const DeleteRequestListData =  [
  {
    key: "1",
    Name: "Darlee Robertson",
    Role: "Facility Manager",
    Image: "avatar-19.jpg",
    ReasonforDeletion: "No longer using service",
    LastActivity: "2 mins ago",
    RequisitionDate: "25 Sep 2025, 12:12 pm",
    DeleteRequestDate: "25 Sep 2025, 12:12 pm",
    Status: "Rejected",
  },
  {
    key: "2",
    Name: "Sharon Roy",
    Role: "Installer",
    Image: "avatar-20.jpg",
    ReasonforDeletion: "Privacy concerns",
    LastActivity: "5 mins ago",
    RequisitionDate: "27 Sep 2025, 07:40 am",
    DeleteRequestDate: "27 Sep 2025, 07:40 am",
    Status: "Pending",
  },
  {
    key: "3",
    Name: "Vaughan Lewis",
    Role: "Senior Manager",
    Image: "avatar-21.jpg",
    ReasonforDeletion: "Duplicate account",
    LastActivity: "2 days ago",
    RequisitionDate: "29 Sep 2025, 08:20 am",
    DeleteRequestDate: "29 Sep 2025, 08:20 am",
    Status: "Rejected",
  },
  {
    key: "4",
    Name: "Jessica Louise",
    Role: "Test Engineer",
    Image: "avatar-23.jpg",
    ReasonforDeletion: "Technical issues",
    LastActivity: "2 mins ago",
    RequisitionDate: "25 Sep 2025, 12:12 pm",
    DeleteRequestDate: "25 Sep 2025, 12:12 pm",
    Status: "Rejected",
  },
  {
    key: "5",
    Name: "Carol Thomas",
    Role: "UI /UX Designer",
    Image: "avatar-16.jpg",
    ReasonforDeletion: "Receiving too many emails",
    LastActivity: "Online",
    RequisitionDate: "02 Oct 2025, 10:10 am",
    DeleteRequestDate: "02 Oct 2025, 10:10 am",
    Status: "Pending",
  },
  {
    key: "6",
    Name: "Dawn Mercha",
    Role: "Technician",
    Image: "avatar-22.jpg",
    ReasonforDeletion: "Privacy concerns",
    LastActivity: "3 days ago",
    RequisitionDate: "17 Oct 2025, 04:25 pm",
    DeleteRequestDate: "17 Oct 2025, 04:25 pm",
    Status: "Pending",
  },
  {
    key: "7",
    Name: "Rachel Hampton",
    Role: "Software Developer",
    Image: "avatar-24.jpg",
    ReasonforDeletion: "Duplicate account",
    LastActivity: "10 days ago",
    RequisitionDate: "28 Oct 2025, 07:16 am",
    DeleteRequestDate: "28 Oct 2025, 07:16 am",
    Status: "Pending",
  },
  {
    key: "8",
    Name: "Jonelle Curtiss",
    Role: "Supervisor",
    Image: "avatar-25.jpg",
    ReasonforDeletion: "No longer using service",
    LastActivity: "1 week go",
    RequisitionDate: "08 Nov 2025, 06:10 am",
    DeleteRequestDate: "08 Nov 2025, 06:10 am",
    Status: "Pending",
  },
  {
    key: "9",
    Name: "Jonathan Smith",
    Role: "Team Lead Dev",
    Image: "avatar-16.jpg",
    ReasonforDeletion: "No longer using service",
    LastActivity: "1 day ago",
    RequisitionDate: "15 Nov 2025, 11:50 am",
    DeleteRequestDate: "15 Nov 2025, 11:50 am",
    Status: "Pending",
  },
  {
    key: "10",
    Name: "Brook Carter",
    Role: "Team Lead Dev",
    Image: "avatar-01.jpg",
    ReasonforDeletion: "Privacy concerns",
    LastActivity: "8 mins ago",
    RequisitionDate: "25 Nov 2025, 06:34 pm",
    DeleteRequestDate: "25 Nov 2025, 06:34 pm",
    Status: "Pending",
  },
];