export const FaqListData = [
  {
    key: "1",
    Questions: "What is a CRM and why should I use it?",
    Category: "Services",
    Answers: "organize contacts, manage sales pipelines, track communication,",
    Createdat: "25 Sep 2025, 01:22 pm",
    Status: "Active",
  },
  {
    key: "2",
    Questions: "How do I add a new contact or company?",
    Category: "Advertising",
    Answers:
      "Go to the Contacts or Companies tab, click “Add New”, and fill in the         form",
    Createdat: "29 Sep 2025, 08:12 am",
    Status: "Active",
  },
  {
    key: "3",
    Questions: "What’s the difference between a Lead, Contact, and Deal?",
    Category: "Services",
    Answers: "A potential customer who hasn't been qualified yet.",
    Createdat: "02 Oct 2025, 02:32 pm",
    Status: "Active",
  },
  {
    key: "4",
    Questions: "How do I track my calls, emails, and meetings?",
    Category: "Services",
    Answers: "You can log activities manually under the contact or deal record",
    Createdat: "11 Oct 2025, 02:32 pm",
    Status: "Active",
  },
  {
    key: "5",
    Questions: "What is the sales pipeline and how do I use it?",
    Category: "Media",
    Answers: "The pipeline shows your deals in different stages",
    Createdat: "04 Nov 2025, 04:22 pm",
    Status: "Active",
  },
  {
    key: "6",
    Questions: "How can I set reminders or follow-up tasks?",
    Category: "Content Marketing",
    Answers:
      "You can create a task under a contact or deal, and set a due date and         reminder.",
    Createdat: "16 Nov 2025, 10:51 pm",
    Status: "Active",
  },
  {
    key: "7",
    Questions: "Can I collaborate with my team in the CRM?",
    Category: "Health Care",
    Answers: "Yes! You can assign deals, tag teammates in notes.",
    Createdat: "25 Nov 2025, 03:43 pm",
    Status: "Active",
  },
  {
    key: "8",
    Questions: "How do I use the CRM on my phone?",
    Category: "Services",
    Answers: "Most CRMs offer a mobile app for iOS and Android.",
    Createdat: "07 Dec 2025, 11:22 am",
    Status: "Active",
  },
  {
    key: "9",
    Questions: "Is my data automatically saved and synced?",
    Category: "Social Marketing",
    Answers:
      "Yes. All updates are saved automatically and synced across devices and         users in real time.",
    Createdat: "15 Dec 2025, 08:17 am",
    Status: "Active",
  },
  {
    key: "10",
    Questions: "Who do I contact if I need help?",
    Category: "Media",
    Answers: "You can reach out to your CRM admin, use the Help Center.",
    Createdat: "29 Dec 2025, 01:22 pm",
    Status: "Active",
  },
];
