export const LeadsDashboardListData = [
  {
    key: "1",
    LeadName: "Collins",
    CompanyName: "NovaWave LLC",
    Location: "Newyork, USA",
    Phone: "+1 875455453",
    Image: "company-icon-01.svg",
    Class: "badge badge-pill bg-pending",
    LeadStatus: "Closed",
  },
  {
    key: "2",
    LeadName: "Konopelski",
    CompanyName: "BlueSky Industries",
    Location: "Winchester, KY",
    Phone: "+1 989757485",
    Image: "company-icon-02.svg",
    Class: "badge badge-pill bg-warning",
    LeadStatus: "Closed",
  },
  {
    key: "3",
    LeadName: "Adams",
    CompanyName: "SilverHawk",
    Location: "Jametown, NY",
    Phone: "+1 546555455",
    Image: "company-icon-03.svg",
    Class: "badge badge-pill bg-warning",
    LeadStatus: "Contacted",
  },
  {
    key: "4",
    LeadName: "Schumm",
    CompanyName: "SummitPeak",
    Location: "Compton, RI",
    Phone: "+1 454478787",
    Image: "company-icon-04.svg",
    Class: "badge badge-pill bg-pending",
    LeadStatus: "Closed",
  },
];
