export const LeadsReportListData = [
  {
    key: "1",
    LeadName: "Elizabeth Morgan",
    CompanyName: "NovaWave LLC",
    Locations: "New York, USA",
    Phone: "+1 875455453",
    LeadStatus: "Closed",
    CreatedDate: "25 Sep 2025, 01:22 pm",
    OwnerImage: "avatar-01.jpg",
    CompanyImage: "company-01.svg",
    LeadImage: "avatar-4.jpg",
    LeadOwner: "Robert Johnson",
  },
  {
    key: "2",
    LeadName: "Katherine Brooks",
    CompanyName: "BlueSky Industries",
    Locations: "Toronto, Canada",
    Phone: "+1 98975 17485",
    LeadStatus: "Not Closed",
    CreatedDate: "03 Feb 2025, 09:45 AM",
    OwnerImage: "avatar-04.jpg",
    CompanyImage: "company-02.svg",
    LeadImage: "avatar-8.jpg",
    LeadOwner: "Isabella Cooper",
  },
  {
    key: "3",
    LeadName: "Samantha Reed",
    CompanyName: "Silver Hawk",
    Locations: "London, UK",
    Phone: "+1 54655 25455",
    LeadStatus: "Closed",
    CreatedDate: "14 Mar 2025, 06:10 PM",
    OwnerImage: "avatar-03.jpg",
    CompanyImage: "company-03.svg",
    LeadImage: "user-02.jpg",
    LeadOwner: "John Smith",
  },
  {
    key: "4",
    LeadName: "William Anderson",
    CompanyName: "Summit  Peak",
    Locations: "Sydney, Australia",
    Phone: "+1 45447 58787",
    LeadStatus: "Contacted",
    CreatedDate: "29 Apr 2025, 11:00 AM",
    OwnerImage: "avatar-07.jpg",
    CompanyImage: "company-04.svg",
    LeadImage: "user-03.jpg",
    LeadOwner: "Sophia Parker",
  },
  {
    key: "5",
    LeadName: "Jonathan Mitchell",
    CompanyName: "RiverStone Ltd",
    Locations: "Berlin, Germany",
    Phone: "+1 12454 27845",
    LeadStatus: "Closed",
    CreatedDate: "07 May 2025, 04:35 PM",
    OwnerImage: "avatar-08.jpg",
    CompanyImage: "company-05.svg",
    LeadImage: "avatar-10.jpg",
    LeadOwner: "Ethan Reynolds",
  },
  {
    key: "6",
    LeadName: "Jennifer Adams",
    CompanyName: "Bright Bridge Grp",
    Locations: "Tokyo, Japan",
    Phone: "+1 47884 75447",
    LeadStatus: "Closed",
    CreatedDate: "18 Jun 2025, 08:20 AM",
    OwnerImage: "avatar-09.jpg",
    CompanyImage: "company-06.svg",
    LeadImage: "user-06.jpg",
    LeadOwner: "Liam Carter",
  },
  {
    key: "7",
    LeadName: "Alexander Carter",
    CompanyName: "CoastalStar Co.",
    Locations: "Paris, France",
    Phone: "+1 21554 34845",
    LeadStatus: "Closed",
    CreatedDate: "18 Apr 2025, 08:00 AM",
    OwnerImage: "avatar-11.jpg",
    CompanyImage: "company-07.svg",
    LeadImage: "user-11.jpg",
    LeadOwner: "Noah Mitchell",
  },
  {
    key: "8",
    LeadName: "Benjamin Harrison",
    CompanyName: "HarborView",
    Locations: "Dubai, UAE",
    Phone: "+1 12114 65471",
    LeadStatus: "Closed",
    CreatedDate: "05 Feb 2025, 10:45 AM",
    OwnerImage: "avatar-16.jpg",
    CompanyImage: "company-08.svg",
    LeadImage: "user-12.jpg",
    LeadOwner: "Mason Hayes",
  },
  {
    key: "9",
    LeadName: "Nicholas Wright",
    CompanyName: "Golden Gate Ltd",
    Locations: "Mumbai, India",
    Phone: "+1 32145 54789",
    LeadStatus: "Closed",
    CreatedDate: "15 Jan 2025, 02:02 PM",
    OwnerImage: "avatar-17.jpg",
    CompanyImage: "company-09.svg",
    LeadImage: "user-14.jpg",
    LeadOwner: "Ron Thompson",
  },
  {
    key: "10",
    LeadName: "Alexandra Bennett",
    CompanyName: "Redwood Inc",
    Locations: "Tokyo, Japan",
    Phone: "+1 27890 17145",
    LeadStatus: "Lost",
    CreatedDate: "12 Mar 2025, 08:00 PM",
    OwnerImage: "avatar-17.jpg",
    CompanyImage: "company-10.svg",
    LeadImage: "user-16.jpg",
    LeadOwner: "James Bennett",
  },
];