export const LeadsListData =[
  {
    key: "1",
    LeadImage: "avatar-19.jpg",
    LeadName: "Darlee Robertson",
    CompanyName: "NovaWave LLC",
    Location: "Newyork, USA",
    CompanyImage: "company-icon-01.svg",
    Phone: "+1 875455453",
    LeadStatus: "Closed",
    LeadOwner: "Jami Carlile",
    OwnerImage: "avatar-13.jpg",
    CreatedDate: "25 Sep 2025, 01:22 pm",
  },
  {
    key: "2",
    LeadImage: "avatar-20.jpg",
    LeadName: "Sharon Roy",
    CompanyName: "BlueSky Industries",
    Location: "Winchester, KY",
    CompanyImage: "company-icon-02.svg",
    Phone: "+1 989757485",
    LeadStatus: "Not Contacted",
    LeadOwner: "Theresa Nelson",
    OwnerImage: "avatar-17.jpg",
    CreatedDate: "29 Sep 2025, 04:15 pm",
  },
  {
    key: "3",
    LeadImage: "avatar-21.jpg",
    LeadName: "Vaughan Lewis",
    CompanyName: "SilverHawk",
    Location: "Jametown, NY",
    CompanyImage: "company-icon-03.svg",
    Phone: "+1 546555455",
    LeadStatus: "Closed",
    LeadOwner: "Smith Cooper",
    OwnerImage: "avatar-14.jpg",
    CreatedDate: "04 Oct 2025, 10:18 am",
  },
  {
    key: "4",
    LeadImage: "avatar-23.jpg",
    LeadName: "Jessica Louise",
    CompanyName: "SummitPeak",
    Location: "Compton, RI",
    CompanyImage: "company-icon-04.svg",
    Phone: "+1 454478787",
    LeadStatus: "Contacted",
    LeadOwner: "Martin Lewis",
    OwnerImage: "avatar-20.jpg",
    CreatedDate: "17 Oct 2025, 03:31 pm",
  },
  {
    key: "5",
    LeadImage: "avatar-16.jpg",
    LeadName: "Carol Thomas",
    CompanyName: "RiverStone Ventur",
    Location: "Dayton, OH",
    CompanyImage: "company-icon-05.svg",
    Phone: "+1 124547845",
    LeadStatus: "Closed",
    LeadOwner: "Newell Egan",
    OwnerImage: "avatar-15.jpg",
    CreatedDate: "24 Oct 2025, 09:14 pm",
  },
  {
    key: "6",
    LeadImage: "avatar-22.jpg",
    LeadName: "Dawn Mercha",
    CompanyName: "Bright Bridge Grp",
    Location: "Lafayette, LA",
    CompanyImage: "company-icon-06.svg",
    Phone: "+1 478845447",
    LeadStatus: "Closed",
    LeadOwner: "Janet Carlson",
    OwnerImage: "avatar-04.jpg",
    CreatedDate: "08 Nov 2025, 09:56 am",
  },
  {
    key: "7",
    LeadImage: "avatar-24.jpg",
    LeadName: "Rachel Hampton",
    CompanyName: "CoastalStar Co.",
    Location: "Centerville, VA",
    CompanyImage: "company-icon-07.svg",
    Phone: "+1 215544845",
    LeadStatus: "Closed",
    LeadOwner: "Craig Brown",
    OwnerImage: "avatar-21.jpg",
    CreatedDate: "14 Nov 2025, 04:19 pm",
  },
  {
    key: "8",
    LeadImage: "avatar-25.jpg",
    LeadName: "Jonelle Curtiss",
    CompanyName: "HarborView",
    Location: "Providence, RI",
    CompanyImage: "company-icon-08.svg",
    Phone: "+1 121145471",
    LeadStatus: "Closed",
    LeadOwner: "Daniel Byrne",
    OwnerImage: "avatar-23.jpg",
    CreatedDate: "23 Nov 2025, 11:14 pm",
  },
  {
    key: "9",
    LeadImage: "avatar-26.jpg",
    LeadName: "Jonathan Smith",
    CompanyName: "Golden Gate Ltd",
    Location: "Swayzee, IN",
    CompanyImage: "company-icon-09.svg",
    Phone: "+1 321454789",
    LeadStatus: "Closed",
    LeadOwner: "Jami Carlile",
    OwnerImage: "avatar-25.jpg",
    CreatedDate: "10 Dec 2025, 06:43 am",
  },
  {
    key: "10",
    LeadImage: "avatar-05.jpg",
    LeadName: "Richard Cooper",
    CompanyName: "Redwood Inc",
    Location: "Florida City, FL",
    CompanyImage: "company-icon-10.svg",
    Phone: "+1 278907145",
    LeadStatus: "Lost",
    LeadOwner: "Theresa Nelson",
    OwnerImage: "avatar-26.jpg",
    CreatedDate: "25 Dec 2025, 08:17 pm",
  },
];