export const ManageuserListData = [
  {
    key: "1",
    Name: "Darlee Robertson",
    Role: "Facility Manager",
    Image: "avatar-19.jpg",
    Phone: "1234567890",
    Email: "robertson@example.com",
    LastActivity: "2 mins ago",
    Created: "25 Sep 2025, 12:12 pm",
    Status: "Active",
  },
  {
    key: "2",
    Name: "Sharon Roy",
    Role: "Installer",
    Image: "avatar-20.jpg",
    Phone: "+1 989757485",
    Email: "sharon@example.com",
    LastActivity: "5 mins ago",
    Created: "27 Sep 2025, 07:40 am",
    Status: "Inactive",
  },
  {
    key: "3",
    Name: "Vaughan Lewis",
    Role: "Senior Manager",
    Image: "avatar-21.jpg",
    Phone: "+1 546555455",
    Email: "vaughan12@example.com",
    LastActivity: "2 days ago",
    Created: "29 Sep 2025, 08:20 am",
    Status: "Active",
  },
  {
    key: "4",
    Name: "Jessica Louise",
    Role: "Test Engineer",
    Image: "avatar-23.jpg",
    Phone: "+1 454478787",
    Email: "jessica13@example.com",
    LastActivity: "2 mins ago",
    Created: "25 Sep 2025, 12:12 pm",
    Status: "Active",
  },
  {
    key: "5",
    Name: "Carol Thomas",
    Role: "UI /UX Designer",
    Image: "avatar-16.jpg",
    Phone: "+1 124547845",
    Email: "caroltho3@example.com",
    LastActivity: "Online",
    Created: "02 Oct 2025, 10:10 am",
    Status: "Active",
  },
  {
    key: "6",
    Name: "Dawn Mercha",
    Role: "Technician",
    Image: "avatar-22.jpg",
    Phone: "+1 478845447",
    Email: "dawnmercha@example.com",
    LastActivity: "3 days ago",
    Created: "17 Oct 2025, 04:25 pm",
    Status: "Active",
  },
  {
    key: "7",
    Name: "Rachel Hampton",
    Role: "Software Developer",
    Image: "avatar-24.jpg",
    Phone: "+1 215544845",
    Email: "rachel@example.com",
    LastActivity: "10 days ago",
    Created: "28 Oct 2025, 07:16 am",
    Status: "Active",
  },
  {
    key: "8",
    Name: "Jonelle Curtiss",
    Role: "Supervisor",
    Image: "avatar-25.jpg",
    Phone: "+1 121145471",
    Email: "jonelle@example.com",
    LastActivity: "1 week go",
    Created: "08 Nov 2025, 06:10 am",
    Status: "Active",
  },
  {
    key: "9",
    Name: "Jonathan Smith",
    Role: "Team Lead Dev",
    Image: "avatar-16.jpg",
    Phone: "+1 321454789",
    Email: "jonathan@example.com",
    LastActivity: "1 day ago",
    Created: "15 Nov 2025, 11:50 am",
    Status: "Active",
  },
  {
    key: "10",
    Name: "Brook Carter",
    Role: "Team Lead Dev",
    Image: "avatar-01.jpg",
    Phone: "+1 278907145",
    Email: "brook@example.com",
    LastActivity: "8 mins ago",
    Created: "25 Nov 2025, 06:34 pm",
    Status: "Active",
  },
];