export const MembershipTransactionsListData =  [
  {
    key: "1",
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "25 Sep 2025, 01:22 PM",
    PaymentType: "Paypal",
    Status: "Completed",
  },
  {
    key: "2",
    Type: "Purchase",
    Amount: "-350",
    Date: "27 Sep 2025, 04:18 PM",
    PaymentType: "Cash",
    Status: "Cancel",
  },
  {
    key: "3",
    Type: "Refund",
    Amount: "+$100",
    Date: "29 Sep 2025, 10:08 AM",
    PaymentType: "Paypal",
    Status: "Completed",
  },
  {
    key: "4",
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "05 Oct 2025, 09:43 AM",
    PaymentType: "Cash",
    Status: "Completed",
  },
  {
    key: "5",
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "17 Oct 2025, 01:22 AM",
    PaymentType: "Paypal",
    Status: "Cancel",
  },
  {
    key: "6",
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "22 Oct 2025, 06:32 PM",
    PaymentType: "Cash",
    Status: "Completed",
  },
  {
    key: "7",
    Type: "Refund",
    Amount: "+$500",
    Date: "05 May 2025, 10:45 AM",
    PaymentType: "Cash",
    Status: "Completed",
  },
  {
    key: "8",
    Type: "Wallet Topup",
    Amount: "+$380",
    Date: "03 May 2025, 09:45 AM",
    PaymentType: "Cash",
    Status: "Completed",
  },
  {
    key: "9",
    Type: "Refund",
    Amount: "+$290",
    Date: "15 Feb 2025, 02:02 PM",
    PaymentType: "PayPal",
    Status: "Completed",
  },
  {
    key: "10",
    Type: "Wallet Topup",
    Amount: "+$380",
    Date: "25 Feb 2025, 01:22 PM",
    PaymentType: "Cash",
    Status: "Completed",
  },
];