export const PermissionListData = [
  {
    key: "1",
    Modules: "Dashboard",
    Sub_Modules: "Dashboard",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "2",
    Modules: "Contacts",
    Sub_Modules: "Contacts",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "3",
    Modules: "Companies",
    Sub_Modules: "Companies",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "4",
    Modules: "Leads",
    Sub_Modules: "Leads",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "5",
    Modules: "Deals",
    Sub_Modules: "Deals",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "6",
    Modules: "Pipelines",
    Sub_Modules: "Pipelines",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "7",
    Modules: "Compaign",
    Sub_Modules: "Compaign",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "8",
    Modules: "Projects",
    Sub_Modules: "Projects",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "9",
    Modules: "Tasks",
    Sub_Modules: "Tasks",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
  {
    key: "10",
    Modules: "Activity",
    Sub_Modules: "Activity",
    Create: "",
    Edit: "",
    View: "",
    Delete: "",
    Allow_All: "",
  },
];
