export const ProjectReportListData = [
  {
    key: "1",
    Name: "Truelysell",
    Image: "project-01.svg",
    Client: "NovaWave LLC",
    ClientImage: "company-01.svg",
    Priority: "High",
    StartDate: "25 Sep 2025",
    EndDate: "15 Oct 2025",
    PipelineStage: "Plan",
    Status: "Active",
  },
  {
    key: "2",
    Name: "Dreamschat",
    Image: "project-02.svg",
    Client: "BlueSky Industries",
    ClientImage: "company-02.svg",
    Priority: "Medium",
    StartDate: "29 Sep 2025",
    EndDate: "19 Oct 2025",
    PipelineStage: "Develop",
    Status: "Inactive",
  },
  {
    key: "3",
    Name: "Truelysell",
    Image: "project-03.svg",
    Client: "SilverHawk",
    ClientImage: "company-03.svg",
    Priority: "Low",
    StartDate: "05 Oct 2025",
    EndDate: "12 Oct 2025",
    PipelineStage: "Completed",
    Status: "Active",
  },
  {
    key: "4",
    Name: "Servbook",
    Image: "project-04.svg",
    Client: "SummitPeak",
    ClientImage: "company-04.svg",
    Priority: "High",
    StartDate: "14 Oct 2025",
    EndDate: "24 Oct 2025",
    PipelineStage: "Design",
    Status: "Inactive",
  },
  {
    key: "5",
    Name: "DreamPOS",
    Image: "project-05.svg",
    Client: "RiverStone Ventur",
    ClientImage: "company-05.svg",
    Priority: "Medium",
    StartDate: "15 Nov 2025",
    EndDate: "22 Nov 2025",
    PipelineStage: "Design",
    Status: "Inactive",
  },
  {
    key: "6",
    Name: "Kofejob",
    Image: "project-06.svg",
    Client: "CoastalStar Co.",
    ClientImage: "company-06.svg",
    Priority: "Low",
    StartDate: "25 Nov 2025",
    EndDate: "09 Dec 2025",
    PipelineStage: "Develop",
    Status: "Active",
  },
  {
    key: "7",
    Name: "Doccure",
    Image: "project-07.svg",
    Client: "HarborView",
    ClientImage: "company-07.svg",
    Priority: "High",
    StartDate: "08 Dec 2025",
    EndDate: "16 Dec 2025",
    PipelineStage: "Completed",
    Status: "Inactive",
  },
  {
    key: "8",
    Name: "Best@laundry",
    Image: "project-08.svg",
    Client: "Golden Gate Ltd",
    ClientImage: "company-08.svg",
    Priority: "Medium",
    StartDate: "21 Dec 2025",
    EndDate: "13 Jan 2024",
    PipelineStage: "Completed",
    Status: "Inactive",
  },
  {
    key: "9",
    Name: "POS",
    Image: "project-09.svg",
    Client: "CoastalStar Inc",
    ClientImage: "company-09.svg",
    Priority: "Low",
    StartDate: "01 Jan 2024",
    EndDate: "11 Jan 2024",
    PipelineStage: "Develop",
    Status: "Inactive",
  },
  {
    key: "10",
    Name: "Bookserv",
    Image: "project-10.svg",
    Client: "Redwood Inc",
    ClientImage: "company-10.svg",
    Priority: "High",
    StartDate: "12 Jan 2024",
    EndDate: "29 Jan 2024",
    PipelineStage: "Develop",
    Status: "Inactive",
  },
];