export const ProposalListData = [
  {
    key: "1",
    ProposalsID: "#1493024",
    Image: "company-icon-01.svg",
    Subject: "SEO Proposal",
    SendTo: "NovaWave LLC",
    TotalValue: "$2,05,426",
    Project: "Truelysell",
    ProjectImage: "truellysel.svg",
    CreatedDate: "21 May 2024",
    Status: "Accepted",
  },
  {
    key: "2",
    ProposalsID: "#1493023",
    Image: "company-icon-02.svg",
    Subject: "Web Design",
    SendTo: "Redwood Inc",
    TotalValue: "$2,105",
    Project: "Dreamsports",
    ProjectImage: "project-01.svg",
    CreatedDate: "15 Apr 2024",
    Status: "Declined",
  },
  {
    key: "3",
    ProposalsID: "#1493022",
    Image: "company-icon-03.svg",
    Subject: "Logo & Branding",
    SendTo: "HarborView",
    TotalValue: "$4,05,656",
    Project: "Best@laundry",
    ProjectImage: "project-01.svg",
    CreatedDate: "12  Mar 2024",
    Status: "Deleted",
  },
  {
    key: "4",
    ProposalsID: "#1493021",
    Image: "company-icon-04.svg",
    Subject: "Development",
    SendTo: "CoastalStar Co.",
    TotalValue: "$2,05,426",
    Project: "Doccure",
    ProjectImage: "project-02.svg",
    CreatedDate: "15 Feb 2024",
    Status: "Draft",
  },
  {
    key: "5",
    ProposalsID: "#1493020",
    Image: "company-icon-05.svg",
    Subject: "SEO Proposal",
    SendTo: "RiverStone Ventur",
    TotalValue: "$3,15,145",
    Project: "Kofejob",
    ProjectImage: "project-01.svg",
    CreatedDate: "15 Jan 2024",
    Status: "Sent",
  },
  {
    key: "6",
    ProposalsID: "#1493019",
    Image: "company-icon-06.svg",
    Subject: "Web Design",
    SendTo: "Summit  Peak",
    TotalValue: "$6,154",
    Project: "DreamPOS",
    ProjectImage: "dream-pos.svg",
    CreatedDate: "15 Dec 2025",
    Status: "Draft",
  },
  {
    key: "7",
    ProposalsID: "#1493018",
    Image: "company-icon-07.svg",
    Subject: "Logo",
    SendTo: "Silver Hawk",
    TotalValue: "$1,457",
    Project: "Servbook",
    ProjectImage: "servebook.svg",
    CreatedDate: "15 Nov 2025",
    Status: "Paused",
  },
  {
    key: "8",
    ProposalsID: "#1493017",
    Image: "company-icon-08.svg",
    Subject: "Branding",
    SendTo: "BlueSky Industries",
    TotalValue: "$2,01,464",
    Project: "Truelysell",
    ProjectImage: "truellysell.svg",
    CreatedDate: "15 Sep 2025",
    Status: "Accepted",
  },
  {
    key: "9",
    ProposalsID: "#1493018",
    Image: "company-icon-09.svg",
    Subject: "Development",
    SendTo: "Golden Gate Ltd",
    TotalValue: "$1,10,145",
    Project: "Dreamschat",
    ProjectImage: "dreamchat.svg",
    CreatedDate: "15 Aug 2025",
    Status: "Declined",
  },
];