export const PurchaseTransactionListData = [
  {
    key: "1",
    InvoiceID: "INV001",
    Image: "company-icon-01.svg",
    Customer: "NovaWave LLC",
    Email: "michael@example.com",
    CreatedDate: "12 Sep 2024",
    Amount: "$200",
    PaymentMethod: "Credit Card",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "2",
    InvoiceID: "INV002",
    Image: "company-icon-02.svg",
    Customer: "BlueSky Industries",
    Email: "sophie@example.com",
    CreatedDate: "24 Oct 2024",
    Amount: "$600",
    PaymentMethod: "Paypal",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "3",
    InvoiceID: "INV003",
    Image: "company-icon-03.svg",
    Customer: "Silver Hawk",
    Email: "cameron@example.com",
    CreatedDate: "18 Feb 2024",
    Amount: "$200",
    PaymentMethod: "Debit Card",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "4",
    InvoiceID: "INV004",
    Image: "company-icon-04.svg",
    Customer: "Summit  Peak",
    Email: "doris@example.com",
    CreatedDate: "17 Oct 2024",
    Amount: "$200",
    PaymentMethod: "Paypal",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "5",
    InvoiceID: "INV005",
    Image: "company-icon-05.svg",
    Customer: "RiverStone Ventur",
    Email: "thomas@example.com",
    CreatedDate: "20 Jul 2024",
    Amount: "$400",
    PaymentMethod: "Credit Card",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "6",
    InvoiceID: "INV006",
    Image: "company-icon-06.svg",
    Customer: "Bright Bridge Grp",
    Email: "kathleen@example.com",
    CreatedDate: "10 Apr 2024",
    Amount: "$200",
    PaymentMethod: "Paypal",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "7",
    InvoiceID: "INV007",
    Image: "company-icon-07.svg",
    Customer: "CoastalStar Co.",
    Email: "bruce@example.com",
    CreatedDate: "29 Aug 2024",
    Amount: "$4800",
    PaymentMethod: "Credit Card",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "8",
    InvoiceID: "INV008",
    Image: "company-icon-08.svg",
    Customer: "HarborView",
    Email: "estelle@example.com",
    CreatedDate: "22 Feb 2024",
    Amount: "$50",
    PaymentMethod: "Credit Card",
    Status: "Unpaid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "9",
    InvoiceID: "INV009",
    Image: "company-icon-09.svg",
    Customer: "Golden Gate Ltd",
    Email: "stephen@example.com",
    CreatedDate: "03 Nov 2024",
    Amount: "$600",
    PaymentMethod: "Paypal",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
  {
    key: "10",
    InvoiceID: "INV010",
    Image: "company-icon-10.svg",
    Customer: "Redwood Inc",
    Email: "angela@example.com",
    CreatedDate: "17 Dec 2024",
    Amount: "$200",
    PaymentMethod: "Credit Card",
    Status: "Paid",
    Action:
      "Preview                                                                                                                                                                   Download                                                                                                                                                                   Delete",
  },
];
