export const StatesListData =  [
  {
    key: "1",
    CountryCode: "US",
    Image: "country-01.svg",
    CountryName: "United States",
    StateName: "Indiana",
  },
  {
    key: "2",
    CountryCode: "CAN",
    Image: "country-02.svg",
    CountryName: "Canada",
    StateName: "Alberta",
  },
  {
    key: "3",
    CountryCode: "ES",
    Image: "country-03.svg",
    CountryName: "Spain",
    StateName: "Madrid",
  },
  {
    key: "4",
    CountryCode: "IN",
    Image: "country-04.svg",
    CountryName: "India",
    StateName: "Tamil Nadu",
  },
  {
    key: "5",
    CountryCode: "BR",
    Image: "country-05.svg",
    CountryName: "Brazil",
    StateName: "Alagoas",
  },
  {
    key: "6",
    CountryCode: "DE",
    Image: "country-06.svg",
    CountryName: "Germany",
    StateName: "Saarland",
  },
  {
    key: "7",
    CountryCode: "MX",
    Image: "country-07.svg",
    CountryName: "Mexico",
    StateName: "Durango",
  },
  {
    key: "8",
    CountryCode: "CN",
    Image: "country-08.svg",
    CountryName: "China",
    StateName: "Shandong",
  },
  {
    key: "9",
    CountryCode: "RU",
    Image: "country-09.svg",
    CountryName: "Russia",
    StateName: "Kalmykia",
  },
  {
    key: "10",
    CountryCode: "IT",
    Image: "country-10.svg",
    CountryName: "Italy",
    StateName: "Tuscany",
  },
];