export const SuperAdminCompanyListData = [
  {
    key: "1",
    Name: "NovaWave LLC",
    Image: "company-icon-01.svg",
    Email: "nova@llc.com",
    AccountURL: "nw.nova.com",
    Plan: "Advanced (Monthly)",
    CreatedDated: "25 Feb 2025, 01:22 PM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "2",
    Name: "BlueSky Industries",
    Image: "company-icon-02.svg",
    Email: "bluesky@ind.com",
    AccountURL: "bl.blue.com",
    Plan: "Enterprise (Monthly)",
    CreatedDated: "03 Apr 2025, 09:45AM",
    Status: "Inactive",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "3",
    Name: "Silver Hawk",
    Image: "company-icon-03.svg",
    Email: "silver@hawk.com",
    AccountURL: "sh.silver.com",
    Plan: "Advanced (Monthly)",
    CreatedDated: "14 Apr 2025, 11:11AM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "4",
    Name: "Summit  Peak",
    Image: "company-icon-04.svg",
    Email: "sumpK@peak.com",
    AccountURL: "sp.summer.com",
    Plan: "Advanced (Monthly)",
    CreatedDated: "12 May 2025, 01:09AM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "5",
    Name: "RiverStone Ventur",
    Image: "company-icon-05.svg",
    Email: "stone@river.com",
    AccountURL: "ro.stone.com",
    Plan: "Basic (Monthly)",
    CreatedDated: "28 May 2025, 07:08AM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "6",
    Name: "Bright Bridge Grp",
    Image: "company-icon-06.svg",
    Email: "bright@grp.com",
    AccountURL: "bb.bright.com",
    Plan: "Enterprise (Monthly)",
    CreatedDated: "01 July 2025, 02:15AM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "7",
    Name: "CoastalStar Co.",
    Image: "company-icon-07.svg",
    Email: "coastal@star.com",
    AccountURL: "cs.coastal.com",
    Plan: "Advanced (Monthly)",
    CreatedDated: "20 Jul 2025, 10:25AM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "8",
    Name: "HarborView",
    Image: "company-icon-08.svg",
    Email: "harbor@view.com",
    AccountURL: "hv.harbor.com",
    Plan: "Advanced (Monthly)",
    CreatedDated: "16 Sep 2025, 02:10 PM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "9",
    Name: "Golden Gate Ltd",
    Image: "company-icon-09.svg",
    Email: "golden@gate.com",
    AccountURL: "ggt.golden.com",
    Plan: "Enterprise (Monthly)",
    CreatedDated: "10 Oct 2025, 10:15AM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
  {
    key: "10",
    Name: "Redwood Inc",
    Image: "company-icon-10.svg",
    Email: "wood@inc.com",
    AccountURL: "ri.redwood.com",
    Plan: "Basic (Monthly)",
    CreatedDated: "01 Nov 2025, 01:32 PM",
    Status: "Active",
    Action:
      "Edit                                                                                                                                                                   Delete                                                                                                                                                                   View",
  },
];
