export const SuperAdminSubscribtionListData = [
  {
    key: "1",
    Subscriber: "NovaWave LLC",
    Image: "company-icon-01.svg",
    Plan: "Advanced (Monthly)",
    BillingCycle: "30 Days",
    PaymentMethod: "Credit Card",
    Amount: "$200",
    CreatedDate: "01 Nov 2025",
    ExpiringOn: "01 Nov 2026",
    Status: "Paid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "2",
    Subscriber: "BlueSky Industries",
    Image: "company-icon-02.svg",
    Plan: "Basic (Yearly)",
    BillingCycle: "365 Days",
    PaymentMethod: "Paypal",
    Amount: "$600",
    CreatedDate: "10 Oct 2025",
    ExpiringOn: "10 Oct 2026",
    Status: "Unpaid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "3",
    Subscriber: "Silver Hawk",
    Image: "company-icon-03.svg",
    Plan: "Advanced (Monthly)",
    BillingCycle: "30 Days",
    PaymentMethod: "Debit Card",
    Amount: "$200",
    CreatedDate: "16 Sep 2025",
    ExpiringOn: "16 Sep 2026",
    Status: "Paid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "4",
    Subscriber: "Summit  Peak",
    Image: "company-icon-04.svg",
    Plan: "Advanced (Monthly)",
    BillingCycle: "30 Days",
    PaymentMethod: "Paypal",
    Amount: "$200",
    CreatedDate: "20 Jul 2025",
    ExpiringOn: "20 Jul 2026",
    Status: "Paid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "5",
    Subscriber: "RiverStone Ventur",
    Image: "company-icon-05.svg",
    Plan: "Enterprise (Monthly)",
    BillingCycle: "30 Days",
    PaymentMethod: "Credit Card",
    Amount: "$400",
    CreatedDate: "17 Jul 2025",
    ExpiringOn: "17 Jul 2026",
    Status: "Unpaid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "6",
    Subscriber: "Bright Bridge Grp",
    Image: "company-icon-06.svg",
    Plan: "Advanced (Monthly)",
    BillingCycle: "30 Days",
    PaymentMethod: "Paypal",
    Amount: "$200",
    CreatedDate: "01 July 2025",
    ExpiringOn: "01 July 2026",
    Status: "Paid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "7",
    Subscriber: "CoastalStar Co.",
    Image: "company-icon-07.svg",
    Plan: "Enterprise (Yearly)",
    BillingCycle: "365 Days",
    PaymentMethod: "Credit Card",
    Amount: "$4800",
    CreatedDate: "28 May 2025",
    ExpiringOn: "28 May 2026",
    Status: "Paid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "8",
    Subscriber: "HarborView",
    Image: "company-icon-08.svg",
    Plan: "Basic (Monthly)",
    BillingCycle: "30 Days",
    PaymentMethod: "Credit Card",
    Amount: "$50",
    CreatedDate: "20 May 2025",
    ExpiringOn: "20 May 2026",
    Status: "Paid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "9",
    Subscriber: "Golden Gate Ltd",
    Image: "company-icon-09.svg",
    Plan: "Basic (Yearly)",
    BillingCycle: "365 Days",
    PaymentMethod: "Paypal",
    Amount: "$600",
    CreatedDate: "12 May 2025",
    ExpiringOn: "12 May 2026",
    Status: "Unpaid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
  {
    key: "10",
    Subscriber: "Redwood Inc",
    Image: "company-icon-10.svg",
    Plan: "Advanced (Monthly)",
    BillingCycle: "30 Days",
    PaymentMethod: "Credit Card",
    Amount: "$200",
    CreatedDate: "14 Apr 2025",
    ExpiringOn: "14 Apr 2026",
    Status: "Paid",
    Action:
      "Download                                                                                                                                                                   Delete                                                                                                                                                                   Preview",
  },
];
