export const testimonialsListData = [
  {
    key: "1",
    EstimationBy: "Darlee Robertson",
    Image:"avatar-19.jpg",
    Role: "Facility Manager",
    Rating: "",
    Content: "Our team cut customer onboarding time by 60% after",
    CreatedDate: "25 Sep 2025, 01:22pm",
    Status: "Inactive",
  },
  {
    key: "2",
    EstimationBy: "Sharon Roy",
        Image:"avatar-20.jpg",
    Role: "Installer",
    Rating: "",
    Content: "Incredibly intuitive, and their support is top-notch.",
    CreatedDate: "29 Sep 2025, 08:12 am",
    Status: "Inactive",
  },
  {
    key: "3",
    EstimationBy: "Vaughan Lewis",
        Image:"avatar-21.jpg",
    Role: " Senior Manager",
    Rating: "",
    Content: "Everything arrived on time, and I’ve already placed.",
    CreatedDate: "02 Oct 2025, 10:15 am",
    Status: "Active",
  },
  {
    key: "4",
    EstimationBy: "Jessica Louise",
       Image:"avatar-22.jpg",
    Role: "Test Engineer",
    Rating: "",
    Content: "The product quality and customer service blew.",
    CreatedDate: "11 Oct 2025, 02:32 pm",
    Status: "Active",
  },
  {
    key: "5",
    EstimationBy: "Carol Thomas",
      Image:"avatar-16.jpg",
    Role: "UI /UX Designer",
    Rating: "",
    Content: "I was hesitant to shop online, but the product quality",
    CreatedDate: "4 Nov 2025, 04:22 pm",
    Status: "Inactive",
  },
  {
    key: "6",
    EstimationBy: "Dawn Mercha",
          Image:"avatar-22.jpg",
    Role: "Technician",
    Rating: "",
    Content: "Strategic advice we got from Apex Consulting",
    CreatedDate: "16 Nov 2025, 10:51 pm",
    Status: "Active",
  },
  {
    key: "8",
    EstimationBy: "Rachel Hampton",
     Image:"avatar-25.jpg",
    Role: "Software Developer",
    Rating: "",
    Content: "The confidence and skills to land my first tech job",
    CreatedDate: "25 Nov 2025, 3:43 pm",
    Status: "Active",
  },
  {
    key: "9",
    EstimationBy: "Jonelle Curtiss",
      Image:"avatar-26.jpg",
    Role: "Supervisor",
    Rating: "",
    Content: "They're now a core part of our growth team.",
    CreatedDate: "07 Dec 2025, 11:22 am",
    Status: "Active",
  },
  {
    key: "10",
    EstimationBy: "Jonathan Smith",
          Image:"avatar-06.jpg",
    Role: "Team Lead Dev",
    Rating: "",
    Content: "The instructors genuinely care, and the real-world",
    CreatedDate: "15 Dec 2025, 8:17 am",
    Status: "Active",
  },
];
