export const TicketsListData =[
  {
    key: "1",
    TicketID: "#TK0020",
    Subject: "Support for theme",
    AssignedImage: "avatar-02.jpg",
    Assigned: "Richard Bennett",
    CreatedOn: "25 Jan 2025, 01:22 PM",
    AssigneeImage: "avatar-19.jpg",
    Assignee: "Darlee Robertson",
    Role: "Facility Manager",
    Priority: "Low",
    Status: "Resolved",
  },
  {
    key: "2",
    TicketID: "#TK0019",
    Subject: "verify your email",
    AssignedImage: "avatar-01.jpg",
    Assigned: "Elizabeth Collins",
    CreatedOn: "03 Feb 2025, 09:45 AM",
    AssigneeImage: "avatar-20.jpg",
    Assignee: "Sharon Roy",
    Role: "Installer",
    Priority: "Medium",
    Status: "Open",
  },
  {
    key: "3",
    TicketID: "#TK0018",
    Subject: "Calling for help",
    AssignedImage: "avatar-04.jpg",
    Assigned: "Michel Dubois",
    CreatedOn: "14 Mar 2025, 06:10 PM",
    AssigneeImage: "avatar-21.jpg",
    Assignee: "Vaughan Lewis",
    Role: "Senior Manager",
    Priority: "High",
    Status: "Pending",
  },
  {
    key: "4",
    TicketID: "#TK0017",
    Subject: "Management",
    AssignedImage: "avatar-03.jpg",
    Assigned: "Esther Williams",
    CreatedOn: "29 Apr 2025, 11:00 AM",
    AssigneeImage: "avatar-23.jpg",
    Assignee: "Jessica Louise",
    Role: "Test Engineer",
    Priority: "Low",
    Status: "Resolved",
  },
  {
    key: "5",
    TicketID: "#TK0016",
    Subject: "Calling for help",
    AssignedImage: "avatar-05.jpg",
    Assigned: "Wilson Clarke",
    CreatedOn: "07 May 2025, 04:35 PM",
    AssigneeImage: "avatar-16.jpg",
    Assignee: "Carol Thomas",
    Role: "UI /UX Designer",
    Priority: "Medium",
    Status: "Open",
  },
  {
    key: "6",
    TicketID: "#TK0015",
    Subject: "Support for theme",
    AssignedImage: "avatar-06.jpg",
    Assigned: "Walter Thompson",
    CreatedOn: "18 Jun 2025, 08:20 AM",
    AssigneeImage: "avatar-22.jpg",
    Assignee: "Dawn Mercha Technician",
    Priority: "High",
    Status: "Pending",
  },
  {
    key: "7",
    TicketID: "#TK0014",
    Subject: "Password Reset",
    AssignedImage: "avatar-07.jpg",
    Assigned: "Noah Mitchell",
    CreatedOn: "18 Apr 2025, 08:00 AM",
    AssigneeImage: "avatar-27.jpg",
    Assignee: "Alexander Carter",
    Role: "Project Manager",
    Priority: "Low",
    Status: "Closed",
  },
  {
    key: "8",
    TicketID: "#TK0013",
    Subject: "Error 502 on Dashboard",
    AssignedImage: "avatar-24.jpg",
    Assigned: "Mason Hayes",
    CreatedOn: "05 Feb 2025, 10:45 AM",
    AssigneeImage: "avatar-16.jpg",
    Assignee: "Benjamin Harrison",
    Role: "Team Lead",
    Priority: "Medium",
    Status: "Resolved",
  },
  {
    key: "9",
    TicketID: "#TK0012",
    Subject: "Plan Upgrade Inquiry",
    AssignedImage: "avatar-25.jpg",
    Assigned: "Ron Thompson",
    CreatedOn: "15 Jan 2025, 02:02 PM",
    AssigneeImage: "avatar-20.jpg",
    Assignee: "Nicholas Wright",
    Role: "Supervisor",
    Priority: "High",
    Status: "Open",
  },
  {
    key: "10",
    TicketID: "#TK0011",
    Subject: "Event Collaboration Request",
    AssignedImage: "avatar-10.jpg",
    Assigned: "James Bennett",
    CreatedOn: "12 Mar 2025, 08:00 PM",
    AssigneeImage: "avatar-16.jpg",
    Assignee: "Alexandra Bennett",
    Role: "Marketing",
    Priority: "Low",
    Status: "Pending",
  },
];