import { all_routes } from "../../routes/all_routes";

const route = all_routes;
export const SidebarData = [
  {
    title: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: route.dealsDashboard,
        submenu: true,
        showSubRoute: false,
        icon: "dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Deals Dashboard", link: route.dealsDashboard },
          { label: "Leads Dashboard", link: route.leadsDashboard },
          { label: "Project Dashboard", link: route.projectDashboard },
        ],
      },
      {
        label: "Applications",
        link: route.chat,
        submenu: true,
        showSubRoute: false,
        icon: "brand-airtable",
        base: "Applications",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Chat", link: route.chat },
          {
            label: "Calls",
            customSubmenuTwo: true,
            submenu: true,
            showSubRoute: false,
            link: route.calls,
            page1: "video-call",
            page2: "audio-call",
            page3: "call-history",
            base: "calls",
            submenuItems: [
              { label: "Video Call", link: route.videoCall, submenu: false, showSubRoute: false, base: "video-call" },
              { label: "Audio Call", link: route.audioCall, submenu: false, showSubRoute: false, base: "audio-call" },
              { label: "Call History", link: route.callHistory, submenu: false, showSubRoute: false, base: "call-history" },
            ],
          },
          { label: "Calendar", link: route.calendar },
          { label: "Email", link: route.email, relatedRoutes: [route.emailReply] },
          { label: "To Do", link: route.todo, relatedRoutes: [route.todoList] },
          { label: "Notes", link: route.notes },
          { label: "File Manager", link: route.fileManager },
          { label: "Social Feed", link: route.socialfeed },
          { label: "Kanban", link: route.kanbanview },
          { label: "Invoices", link: route.invoice, relatedRoutes: [route.invoice_details] },
        ],
      },
      {
        label: "Super Admin",
        link: route.superadminDashboard,
        submenu: true,
        showSubRoute: false,
        icon: "user-star",
        base: "Super Admin",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Dashboard", link: route.superadminDashboard },
          { label: "Companies", link: route.superadminCompany },
          { label: "Subscriptions", link: route.superadminSubscription },
          { label: "Packages", link: route.superadminPackagelist },
          { label: "Domain", link: route.superadminDomain },
          { label: "Purchase Transaction", link: route.superadminPurchaseTransaction },
        ],
      },
      {
        label: "Layouts",
        link: route.layoutMini,
        submenu: true,
        showSubRoute: false,
        icon: "layout-grid",
        base: "Layouts",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Mini", link: route.layoutMini },
          { label: "Hover View", link: route.hoverView },
          { label: "Hidden", link: route.hidden },
          { label: "Full Width", link: route.fullWidth },
          { label: "RTL", link: route.layoutRtl },
          { label: "Dark", link: route.Dark },
        ],
      },
    ],
  },

  // ─── BILLING APPLICATION ────────────────────────────────────────────────────
  {
    title: "Billing Application",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Product Settings",
        link: route.productPreference,
        submenu: true,
        showSubRoute: false,
        icon: "package",
        base: "Product Settings",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Product Preference", link: route.productPreference },
        ],
      },
      {
        label: "Products",
        link: route.productList,
        submenu: true,
        showSubRoute: false,
        icon: "box",
        base: "Products",
        materialicons: "start",
        dot: true,
        submenuItems: [
          {
            label: "Product List",
            link: route.productList,
            relatedRoutes: [route.product],
          },
          {
            label: "Locations",
            link: route.locations,
            relatedRoutes: [route.locations],
          },
          {
            label: "Price Lists",
            link: route.priceList,
            relatedRoutes: [route.priceList],
            submenu: false,
            showSubRoute: false,
            icon: "file-spreadsheet",
            base: "frontent",
            materialicons: "start",
            dot: true,
            submenuItems: [],
          },
          {
            label: "Composite Items",
            link: route.compositeItems,
            relatedRoutes: [route.compositeItems, route.compositeItemAdd, route.compositeItemEdit],
            submenu: false,
            showSubRoute: false,
            icon: "layout-grid",
            base: "frontent",
            materialicons: "start",
            dot: true,
            submenuItems: [],
          },
        ],
      },
    ],
  },

  // ─── CRM ────────────────────────────────────────────────────────────────────
  {
    title: "CRM",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Contacts",
        link: route.contactGrid,
        relatedRoutes: [route.contactGrid, route.contactList, route.contactDetails],
        submenu: false,
        showSubRoute: false,
        icon: "user-up",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Companies",
        link: route.companiesGrid,
        relatedRoutes: [route.companiesGrid, route.companiesList, route.companiesDetails],
        submenu: false,
        showSubRoute: false,
        icon: "building-community",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Deals",
        link: route.dealsGrid,
        relatedRoutes: [route.dealsGrid, route.dealsList, route.dealsDetails],
        submenu: false,
        showSubRoute: false,
        icon: "medal",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Leads",
        link: route.leads,
        relatedRoutes: [route.leads, route.leadsList, route.leadsDetails],
        submenu: false,
        showSubRoute: false,
        icon: "chart-arcs",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Pipeline",
        link: route.pipeline,
        submenu: false,
        showSubRoute: false,
        icon: "timeline-event-exclamation",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Campaign",
        link: route.campaign,
        relatedRoutes: [route.campaign, route.campaignComplete, route.campaignArchieve],
        submenu: false,
        showSubRoute: false,
        icon: "brand-campaignmonitor",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Projects",
        link: route.projectsGrid,
        relatedRoutes: [route.projectsGrid, route.projectsList, route.projectDetails],
        submenu: false,
        showSubRoute: false,
        icon: "atom-2",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Tasks",
        link: route.tasks,
        relatedRoutes: [route.tasks, route.tasksImportant, route.tasksCompleted],
        submenu: false,
        showSubRoute: false,
        icon: "list-check",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Proposals",
        link: route.ProposalsGrid,
        relatedRoutes: [route.ProposalsGrid, route.ProposalsList, route.ProposalsView],
        submenu: false,
        showSubRoute: false,
        icon: "file-star",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Contracts",
        link: route.ContractsGrid,
        relatedRoutes: [route.ContractsGrid, route.ContractsList],
        submenu: false,
        showSubRoute: false,
        icon: "file-check",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Estimations",
        link: route.estimationKanban,
        relatedRoutes: [route.estimationKanban, route.estimationList],
        submenu: false,
        showSubRoute: false,
        icon: "file-report",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoices",
        link: route.InvoiceGrid,
        relatedRoutes: [route.InvoiceGrid, route.InvoiceList, route.invoice_details],
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Payments",
        link: route.payments,
        submenu: false,
        showSubRoute: false,
        icon: "report-money",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Analytics",
        link: route.analytics,
        submenu: false,
        showSubRoute: false,
        icon: "chart-bar",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Activities",
        link: route.activities,
        relatedRoutes: [route.activityCalls, route.activityMail, route.activityTask, route.activityMeeting],
        submenu: false,
        showSubRoute: false,
        icon: "bounce-right",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },

  // ─── REPORTS ────────────────────────────────────────────────────────────────
  {
    title: "Reports",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Reports",
        link: route.leadReports,
        submenu: true,
        showSubRoute: false,
        icon: "report-analytics",
        base: "Reports",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Lead Reports", link: route.leadReports },
          { label: "Deal Reports", link: route.dealReports },
          { label: "Contact Reports", link: route.contactReports },
          { label: "Company Reports", link: route.companyReports },
          { label: "Project Reports", link: route.projectReports },
          { label: "Task Reports", link: route.taskReports },
        ],
      },
    ],
  },

  // ─── CRM SETTINGS ───────────────────────────────────────────────────────────
  {
    title: "CRM Settings",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      { label: "Sources", link: route.sources, submenu: false, showSubRoute: false, icon: "artboard", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Lost Reason", link: route.lostReason, submenu: false, showSubRoute: false, icon: "message-exclamation", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Contact Stage", link: route.contactStage, submenu: false, showSubRoute: false, icon: "steam", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Industry", link: route.industry, submenu: false, showSubRoute: false, icon: "building-factory", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Calls", link: route.calls, submenu: false, showSubRoute: false, icon: "phone-check", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
    ],
  },

  // ─── USER MANAGEMENT ────────────────────────────────────────────────────────
  {
    title: "User Management",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      { label: "Manage Users", link: route.manageusers, submenu: false, showSubRoute: false, icon: "users", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Roles & Permissions", link: route.rolesPermissions, relatedRoutes: [route.rolesPermissions, route.permissions], submenu: false, showSubRoute: false, icon: "user-shield", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Delete Request", link: route.deleteRequest, submenu: false, showSubRoute: false, icon: "flag-question", base: "frontent", materialicons: "start", dot: true, submenuItems: [] },
    ],
  },

  // ─── MEMBERSHIP ─────────────────────────────────────────────────────────────
  {
    title: "Membership",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Membership",
        link: route.membershipplan,
        submenu: true,
        showSubRoute: false,
        icon: "brand-apple-podcast",
        base: "Membership",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Membership Plans", link: route.membershipplan },
          { label: "Membership Addons", link: route.membershipAddon },
          { label: "Transactions", link: route.membershipTransaction },
        ],
      },
    ],
  },

  // ─── CONTENT ────────────────────────────────────────────────────────────────
  {
    title: "Content",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      { label: "Pages", link: route.pages, submenu: false, showSubRoute: false, icon: "page-break", base: "Pages", materialicons: "start", dot: true, submenuItems: [] },
      {
        label: "Blog", link: route.blog, submenu: true, showSubRoute: false, icon: "brand-blogger", base: "Blog", materialicons: "start", dot: true,
        submenuItems: [
          { label: "All Blogs", link: route.blog },
          { label: "Blog Categories", link: route.blogCategories },
          { label: "Blog Comments", link: route.blogComment },
          { label: "Blog Tags", link: route.blogTags },
        ],
      },
      {
        label: "Location", link: route.countries, submenu: true, showSubRoute: false, icon: "map-pin-pin", base: "Location", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Countries", link: route.countries },
          { label: "States", link: route.states },
          { label: "Cities", link: route.cities },
        ],
      },
      { label: "Testimonials", link: route.testimonials, submenu: false, showSubRoute: false, icon: "quote", base: "Testimonials", materialicons: "start", dot: true, submenuItems: [] },
      { label: "FAQ", link: route.faq, submenu: false, showSubRoute: false, icon: "question-mark", base: "FAQ", materialicons: "start", dot: true, submenuItems: [] },
    ],
  },

  // ─── SUPPORT ────────────────────────────────────────────────────────────────
  {
    title: "Support",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      { label: "Contact Messages", link: route.contactMessages, submenu: false, showSubRoute: false, icon: "message-check", base: "Contact Messages", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Tickets", link: route.tickets, submenu: false, showSubRoute: false, icon: "ticket", base: "Tickets", materialicons: "start", dot: true, submenuItems: [] },
    ],
  },

  // ─── SETTINGS ───────────────────────────────────────────────────────────────
  {
    title: "Settings",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "General Settings", link: route.profile, submenu: true, showSubRoute: false, icon: "settings-cog", base: "General Settings", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Profile", link: route.profile },
          { label: "Security", link: route.security },
          { label: "Notifications", link: route.notification },
          { label: "Connected Apps", link: route.connectedApps },
        ],
      },
      {
        label: "Website Settings", link: route.companySettings, submenu: true, showSubRoute: false, icon: "world-cog", base: "Website Settings", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Company Settings", link: route.companySettings },
          { label: "Localization", link: route.localization },
          { label: "Prefixes", link: route.prefixes },
          { label: "Preference", link: route.preference },
          { label: "Appearance", link: route.appearance },
          { label: "Language", link: route.languageWeb },
        ],
      },
      {
        label: "App Settings", link: route.invoiceSettings, submenu: true, showSubRoute: false, icon: "apps", base: "App Settings", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Invoice Settings", link: route.invoiceSettings },
          { label: "Printers", link: route.printers },
          { label: "Custom Fields", link: route.customFields },
        ],
      },
      {
        label: "System Settings", link: route.superadminDashboard, submenu: true, showSubRoute: false, icon: "device-laptop", base: "System Settings", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Email Settings", link: route.emailSettings },
          { label: "SMS Gateways", link: route.smsGateways },
          { label: "GDPR Cookies", link: route.gdprCookies },
        ],
      },
      {
        label: "Financial Settings", link: route.paymentGateways, submenu: true, showSubRoute: false, icon: "moneybag", base: "Financial Settings", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Payment Gateways", link: route.paymentGateways },
          { label: "Bank Accounts", link: route.bankAccount },
          { label: "Tax Rates", link: route.taxRates },
          { label: "Currencies", link: route.currencies },
        ],
      },
      {
        label: "Other Settings", link: route.sitemap, submenu: true, showSubRoute: false, icon: "settings-2", base: "Other Settings", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Sitemap", link: route.sitemap },
          { label: "Clear Cache", link: route.clearCache },
          { label: "Storage", link: route.storage },
          { label: "Cronjob", link: route.cronjob },
          { label: "Ban IP Address", link: route.banIpAddrress },
          { label: "System Backup", link: route.systemBackup },
          { label: "Database Backup", link: route.databaseBackup },
          { label: "System Update", link: route.systemUpdate },
        ],
      },
    ],
  },

  // ─── PAGES ──────────────────────────────────────────────────────────────────
  {
    title: "Pages",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Authentication", link: route.login, submenu: true, showSubRoute: false, icon: "lock-square-rounded", base: "Authentication", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Login", link: route.login },
          { label: "Register", link: route.register },
          { label: "Forgot Password", link: route.forgotPassword },
          { label: "Reset Password", link: route.resetPassword },
          { label: "Email Verification", link: route.emailVerification },
          { label: "2 Step Verification", link: route.twoStepVerification },
          { label: "Lock Screen", link: route.lockScreen },
        ],
      },
      {
        label: "Error Pages", link: route.error404, submenu: true, showSubRoute: false, icon: "error-404", base: "Error Pages", materialicons: "start", dot: true,
        submenuItems: [
          { label: "404 Error", link: route.error404 },
          { label: "500 Error", link: route.error500 },
        ],
      },
      { label: "Blank Page", link: route.blankPage, submenu: false, showSubRoute: false, icon: "file", base: "Blank Page", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Coming Soon", link: route.comingSoon, submenu: false, showSubRoute: false, icon: "inner-shadow-top-right", base: "Coming Soon", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Under Maintenance", link: route.underMaintenance, submenu: false, showSubRoute: false, icon: "info-triangle", base: "Under Maintenance", materialicons: "start", dot: true, submenuItems: [] },
    ],
  },

  // ─── UI INTERFACE ───────────────────────────────────────────────────────────
  {
    title: "UI Interface",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Base UI", link: route.accordion, submenu: true, showSubRoute: false, icon: "hierarchy", base: "Base Ui", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Accordion", link: route.accordion },
          { label: "Alerts", link: route.uiAlerts },
          { label: "Avatar", link: route.uiAvatar },
          { label: "Badges", link: route.uiBadges },
          { label: "Breadcrumb", link: route.uiBreadcrumb },
          { label: "Buttons", link: route.uiButtons },
          { label: "Button Group", link: route.uiButtonsGroup },
          { label: "Card", link: route.uiCards },
          { label: "Carousel", link: route.uiCarousel },
          { label: "Collapse", link: route.uiCollapse },
          { label: "Dropdowns", link: route.uiDropdowns },
          { label: "Ratio", link: route.uiRatio },
          { label: "Grid", link: route.uiGrid },
          { label: "Images", link: route.uiImage },
          { label: "Links", link: route.uiLinks },
          { label: "List Group", link: route.uiListGroup },
          { label: "Modals", link: route.uiModals },
          { label: "Offcanvas", link: route.offcanvas },
          { label: "Pagination", link: route.pagination },
          { label: "Placeholders", link: route.placeholder },
          { label: "Popovers", link: route.popover },
          { label: "Progress", link: route.progress },
          { label: "Scrollspy", link: route.uiScrollspy },
          { label: "Spinner", link: route.spinner },
          { label: "Tabs", link: route.navTabs },
          { label: "Toasts", link: route.toasts },
          { label: "Tooltips", link: route.tooltip },
          { label: "Typography", link: route.typography },
          { label: "Utilities", link: route.uiUtilities },
        ],
      },
      {
        label: "Advanced UI", link: route.dragandDrop, submenu: true, showSubRoute: false, icon: "whirl", base: "Advanced Ui", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Dragula", link: route.dragandDrop },
          { label: "Clipboard", link: route.clipboard },
          { label: "Range Slider", link: route.rangeSlider },
          { label: "Sweet Alerts", link: route.sweetalert },
          { label: "Lightbox", link: route.lightbox },
          { label: "Rating", link: route.rating },
          { label: "Scrollbar", link: route.scrollBar },
        ],
      },
      {
        label: "Forms", link: route.basicInput, submenu: true, showSubRoute: false, icon: "forms", base: "Forms", materialicons: "start", dot: true,
        submenuItems: [
          {
            label: "Form Elements", customSubmenuTwo: true, submenu: true, showSubRoute: false, link: route.basicInput,
            page1: "Basic Inputs", page2: "Checkbox & Radios", page3: "Input Groups", page4: "Grid & Gutters", page5: "Input Masks", page6: "File Uploads", base: "Form Elements",
            submenuItems: [
              { label: "Basic Inputs", link: route.basicInput, submenu: false, showSubRoute: false, base: "Basic Inputs" },
              { label: "Checkbox & Radios", link: route.checkboxandRadios, submenu: false, showSubRoute: false, base: "Checkbox & Radios" },
              { label: "Input Groups", link: route.inputGroup, submenu: false, showSubRoute: false, base: "Input Groups" },
              { label: "Grid & Gutters", link: route.gridandGutters, submenu: false, showSubRoute: false, base: "Grid & Gutters" },
              { label: "Input Masks", link: route.formMask, submenu: false, showSubRoute: false, base: "Input Masks" },
              { label: "File Uploads", link: route.fileUpload, submenu: false, showSubRoute: false, base: "File Uploads" },
            ],
          },
          {
            label: "Layouts", customSubmenuTwo: true, submenu: true, showSubRoute: false, link: route.horizontalForm,
            page1: "Horizontal Form", page2: "Vertical Form", page3: "Floating Labels", base: "Layouts",
            submenuItems: [
              { label: "Horizontal Form", link: route.horizontalForm, submenu: false, showSubRoute: false, base: "Horizontal Form" },
              { label: "Vertical Form", link: route.verticalForm, submenu: false, showSubRoute: false, base: "Vertical Form" },
              { label: "Floating Labels", link: route.floatingLable, submenu: false, showSubRoute: false, base: "Floating Labels" },
            ],
          },
          { label: "Form Validation", link: route.formValidation },
          { label: "Form Select", link: route.formSelect },
          { label: "Form Wizard", link: route.formWizard },
          { label: "Form Picker", link: route.formpicker },
        ],
      },
      {
        label: "Tables", link: route.dataTables, submenu: true, showSubRoute: false, icon: "table", base: "Tables", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Data Table", link: route.dataTables },
          { label: "Basic Tables", link: route.tablesBasic },
        ],
      },
      {
        label: "Charts", link: route.apexChat, submenu: true, showSubRoute: false, icon: "chart-pie-3", base: "Charts", materialicons: "start", dot: true,
        submenuItems: [{ label: "Apex Charts", link: route.apexChat }],
      },
      {
        label: "Icons", link: route.fantawesome, submenu: true, showSubRoute: false, icon: "icons", base: "Icons", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Fontawesome Icons", link: route.fantawesome },
          { label: "Tabler Icons", link: route.tablericons },
          { label: "Bootstrap Icons", link: route.bootstrapicons },
          { label: "Remix Icons", link: route.remixicons },
          { label: "Ionic Icons", link: route.iconicIcon },
          { label: "Material Icons", link: route.materialIcon },
          { label: "Pe7 Icons", link: route.pe7icon },
          { label: "Themify Icons", link: route.themifyIcon },
          { label: "Weather Icons", link: route.weatherIcon },
          { label: "Typicon Icons", link: route.typicon },
          { label: "Flag Icons", link: route.falgIcons },
        ],
      },
      {
        label: "Maps", link: route.mapleaflet, submenu: true, showSubRoute: false, icon: "map-star", base: "Maps", materialicons: "start", dot: true,
        submenuItems: [{ label: "Leaflet", link: route.mapleaflet }],
      },
    ],
  },

  // ─── HELP ───────────────────────────────────────────────────────────────────
  {
    title: "Help",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      { label: "Documentation", link: "#", submenu: false, showSubRoute: false, icon: "file-stack", base: "Documentation", materialicons: "start", dot: true, submenuItems: [] },
      { label: "Changelog v2.2.7", link: "#", submenu: false, showSubRoute: false, icon: "arrow-capsule", base: "Changelog v2.2.7", materialicons: "start", dot: true, submenuItems: [] },
      {
        label: "Multi Level", link: "#", submenu: true, showSubRoute: false, icon: "menu-deep", base: "Multi Level", materialicons: "start", dot: true,
        submenuItems: [
          { label: "Level 1.1", link: "#", submenu: false, showSubRoute: false, base: "Level 1.1" },
          {
            label: "Level 1.2", customSubmenuTwo: true, submenu: true, showSubRoute: false, link: "#",
            page1: "Level 2.1", page2: "Level 2.2", base: "Level 1.2",
            submenuItems: [
              { label: "Level 2.1", link: "#", submenu: false, showSubRoute: false, base: "Level 2.1" },
            ],
          },
        ],
      },
    ],
  },
];